-- Leega
-- 28/11/2016
-- csiprova1 relays

--
-- Aggiunta manuale dati meeting 16101 per la tabella meeting_programs
-- 
INSERT INTO meeting_programs (id,event_order,user_id,meeting_event_id,gender_type_id,category_type_id,pool_type_id,time_standard_id,lock_version,created_at,updated_at) VALUES 
(83132,5,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16101 and et.code = 'S4X50MI'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = '001-119' and t.season_id = 161),(select t.id from pool_types t where t.code = '25'),(select max(ts.id) from time_standards ts where ts.season_id = 161 and ts.gender_type_id = (select t.id from gender_types t where t.code = 'F') and ts.event_type_id = (select t.id from event_types t where t.code = 'S4X50MI') and ts.category_type_id = (select t.id from category_types t where t.code = '001-119' and t.season_id = 161) and ts.pool_type_id = (select t.id from pool_types t where t.code = '25')),0,CURDATE(),CURDATE()),
(83133,5,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16101 and et.code = 'S4X50MI'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = '001-119' and t.season_id = 161),(select t.id from pool_types t where t.code = '25'),(select max(ts.id) from time_standards ts where ts.season_id = 161 and ts.gender_type_id = (select t.id from gender_types t where t.code = 'M') and ts.event_type_id = (select t.id from event_types t where t.code = 'S4X50MI') and ts.category_type_id = (select t.id from category_types t where t.code = '001-119' and t.season_id = 161) and ts.pool_type_id = (select t.id from pool_types t where t.code = '25')),0,CURDATE(),CURDATE()),
(83134,5,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16101 and et.code = 'S4X50MI'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = '120-159' and t.season_id = 161),(select t.id from pool_types t where t.code = '25'),(select max(ts.id) from time_standards ts where ts.season_id = 161 and ts.gender_type_id = (select t.id from gender_types t where t.code = 'F') and ts.event_type_id = (select t.id from event_types t where t.code = 'S4X50MI') and ts.category_type_id = (select t.id from category_types t where t.code = '120-159' and t.season_id = 161) and ts.pool_type_id = (select t.id from pool_types t where t.code = '25')),0,CURDATE(),CURDATE()),
(83135,5,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16101 and et.code = 'S4X50MI'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = '120-159' and t.season_id = 161),(select t.id from pool_types t where t.code = '25'),(select max(ts.id) from time_standards ts where ts.season_id = 161 and ts.gender_type_id = (select t.id from gender_types t where t.code = 'M') and ts.event_type_id = (select t.id from event_types t where t.code = 'S4X50MI') and ts.category_type_id = (select t.id from category_types t where t.code = '120-159' and t.season_id = 161) and ts.pool_type_id = (select t.id from pool_types t where t.code = '25')),0,CURDATE(),CURDATE()),
(83136,5,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16101 and et.code = 'S4X50MI'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = '160-999' and t.season_id = 161),(select t.id from pool_types t where t.code = '25'),(select max(ts.id) from time_standards ts where ts.season_id = 161 and ts.gender_type_id = (select t.id from gender_types t where t.code = 'F') and ts.event_type_id = (select t.id from event_types t where t.code = 'S4X50MI') and ts.category_type_id = (select t.id from category_types t where t.code = '160-999' and t.season_id = 161) and ts.pool_type_id = (select t.id from pool_types t where t.code = '25')),0,CURDATE(),CURDATE()),
(83137,5,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16101 and et.code = 'S4X50MI'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = '160-999' and t.season_id = 161),(select t.id from pool_types t where t.code = '25'),(select max(ts.id) from time_standards ts where ts.season_id = 161 and ts.gender_type_id = (select t.id from gender_types t where t.code = 'M') and ts.event_type_id = (select t.id from event_types t where t.code = 'S4X50MI') and ts.category_type_id = (select t.id from category_types t where t.code = '160-999' and t.season_id = 161) and ts.pool_type_id = (select t.id from pool_types t where t.code = '25')),0,CURDATE(),CURDATE());


INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20911,1,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 1),2,20,10,1,24,0,83132,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20912,10,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 10),2,26,20,2,21,0,83132,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20913,21,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 21),2,36,10,3,18,0,83132,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20914,826,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 826),2,43,00,4,15,0,83132,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20915,35,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 35),2,46,70,5,12,0,83132,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20916,18,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 18),3,03,10,6,9,0,83132,2);

INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20917,21,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 21),1,59,60,1,24,0,83133,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20918,10,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 10),2,04,80,2,21,0,83133,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20919,5,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 5),2,06,00,3,18,0,83133,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20920,35,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 35),2,13,10,4,15,0,83133,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20921,1000,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 1000),2,14,50,5,12,0,83133,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20922,18,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 18),2,15,80,6,9,0,83133,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20923,1,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 1),2,21,00,7,6,0,83133,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20924,10,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 10),2,25,70,8,0,0,83133,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20925,290,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 290),2,44,40,9,2,0,83133,2);

INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20926,1,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 1),2,29,80,1,24,0,83134,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20927,5,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 5),2,30,50,2,21,0,83134,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20928,11,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 11),2,50,90,3,18,0,83134,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20929,14,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 14),2,55,40,4,15,0,83134,2);

INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20930,11,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 11),2,07,70,1,24,0,83135,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20931,5,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 5),2,10,80,2,21,0,83135,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20932,1,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 1),2,11,60,3,18,0,83135,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20933,826,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 826),2,17,50,4,15,0,83135,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20934,10,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 10),2,31,10,5,12,0,83135,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20935,18,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 18),2,31,40,6,9,0,83135,2);

INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20936,10,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 10),2,28,60,1,24,0,83136,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20937,5,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 5),2,37,70,2,21,0,83136,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20938,18,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 18),2,38,70,3,18,0,83136,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20939,1,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 1),2,47,40,4,15,0,83136,2);

INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20940,1,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 1),2,13,10,1,24,0,83137,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20941,5,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 5),2,13,10,1,24,0,83137,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20942,14,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 14),2,16,60,3,18,0,83137,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20943,11,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 11),2,17,00,4,15,0,83137,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20944,5,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 5),2,23,60,5,0,0,83137,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20945,4,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 4),2,35,00,6,9,0,83137,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20946,1,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 1),2,37,00,7,0,0,83137,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20947,18,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 18),2,48,40,8,3,0,83137,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20948,826,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 826),3,10,80,9,2,0,83137,2);
INSERT INTO meeting_relay_results (id,team_id,team_affiliation_id,minutes,seconds,hundreds,rank,meeting_points,is_disqualified,meeting_program_id,user_id) VALUES (20949,4,(select ta.id from team_affiliations ta where ta.season_id = 161 and ta.team_id = 4),0,0,0,0,0,1,83137,2);
