--
-- PassagesBatchUpdater: recorded from actions by [User: leega (Marco Ligabue) ID: 2]
-- 22 January 2017 11:10:08
-- Begin script
--

INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6296, 0, 42, 26, 75873, 2, 2, '2017-01-22 10:10:08', '2017-01-22 10:10:08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 42, 26, 0, 444848, NULL, 192, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6297, 0, 48, 64, 75873, 4, 2, '2017-01-22 10:10:08', '2017-01-22 10:10:08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 30, 90, 0, 444848, NULL, 192, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6298, 0, 39, 3, 75872, 2, 2, '2017-01-22 10:10:08', '2017-01-22 10:10:08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 39, 3, 0, 444838, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6299, 0, 43, 37, 75872, 4, 2, '2017-01-22 10:10:08', '2017-01-22 10:10:08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 22, 40, 0, 444838, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6300, 0, 39, 18, 75872, 2, 2, '2017-01-22 10:10:08', '2017-01-22 10:10:08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 39, 18, 0, 444837, NULL, 98, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6301, 0, 42, 22, 75872, 4, 2, '2017-01-22 10:10:08', '2017-01-22 10:10:08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 21, 40, 0, 444837, NULL, 98, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6302, 0, 37, 16, 75868, 2, 2, '2017-01-22 10:10:08', '2017-01-22 10:10:08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 37, 16, 0, 444826, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6303, 0, 41, 84, 75868, 4, 2, '2017-01-22 10:10:08', '2017-01-22 10:10:08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 19, 0, 0, 444826, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6304, 0, 36, 92, 75886, 2, 2, '2017-01-22 10:10:08', '2017-01-22 10:10:08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 36, 92, 0, 444953, NULL, 64, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6305, 0, 41, 68, 75886, 4, 2, '2017-01-22 10:10:08', '2017-01-22 10:10:08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 18, 60, 0, 444953, NULL, 64, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6306, 0, 30, 23, 75879, 2, 2, '2017-01-22 10:10:08', '2017-01-22 10:10:08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 30, 23, 0, 444870, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6307, 0, 33, 7, 75879, 4, 2, '2017-01-22 10:10:08', '2017-01-22 10:10:08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 3, 30, 0, 444870, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6308, 0, 42, 73, 75897, 2, 2, '2017-01-22 10:10:08', '2017-01-22 10:10:08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 42, 73, 0, 444988, NULL, 1805, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6309, 0, 53, 50, 75897, 4, 2, '2017-01-22 10:10:08', '2017-01-22 10:10:08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 95, 123, 0, 444988, NULL, 1805, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6310, 0, 58, 66, 75897, 6, 2, '2017-01-22 10:10:09', '2017-01-22 10:10:09', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 94, 89, 0, 444988, NULL, 1805, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6311, 0, 44, 11, 75897, 8, 2, '2017-01-22 10:10:09', '2017-01-22 10:10:09', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 19, 0, 0, 444988, NULL, 1805, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6312, 0, 37, 96, 75896, 2, 2, '2017-01-22 10:10:09', '2017-01-22 10:10:09', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 37, 96, 0, 444981, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6313, 0, 58, 51, 75896, 4, 2, '2017-01-22 10:10:09', '2017-01-22 10:10:09', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 95, 147, 0, 444981, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6314, 0, 46, 87, 75896, 6, 2, '2017-01-22 10:10:09', '2017-01-22 10:10:09', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 82, 134, 0, 444981, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6315, 0, 35, 16, 75896, 8, 2, '2017-01-22 10:10:09', '2017-01-22 10:10:09', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 58, 50, 0, 444981, NULL, 1409, 1);
