-- Leega
-- 18/01/2017
-- Gussago program fix - second chance

-- Add missing events
INSERT INTO meeting_events (id,event_order,is_out_of_race,meeting_session_id,event_type_id,heat_type_id,user_id,lock_version,created_at,updated_at) values  (12023,16,0,(select t.id from meeting_sessions t where t.meeting_id = 16205 and t.session_order = 1),(select t.id from event_types t where t.code = '100FA'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE());
INSERT INTO meeting_events (id,event_order,is_out_of_race,meeting_session_id,event_type_id,heat_type_id,user_id,lock_version,created_at,updated_at) values  (12024,17,0,(select t.id from meeting_sessions t where t.meeting_id = 16205 and t.session_order = 1),(select t.id from event_types t where t.code = '200DO'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE());
INSERT INTO meeting_events (id,event_order,is_out_of_race,meeting_session_id,event_type_id,heat_type_id,user_id,lock_version,created_at,updated_at) values  (12025,18,0,(select t.id from meeting_sessions t where t.meeting_id = 16205 and t.session_order = 1),(select t.id from event_types t where t.code = '50RA'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE());


--
-- Aggiornamento programma gare per il meeting 16205
-- 
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 1), event_order = 1 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '100RA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 1), event_order = 2 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '50SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 1), event_order = 3 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '200FA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 1), event_order = 4 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '100MI') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 1), event_order = 5 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '100DO') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 2), event_order = 6 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '200RA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 2), event_order = 7 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '50DO') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 2), event_order = 8 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '200MI') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 2), event_order = 9 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '50FA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 2), event_order = 10 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '100SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 2), event_order = 11 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = 'M4X50MI') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 3), event_order = 12 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '200SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 3), event_order = 13 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '50RA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 3), event_order = 14 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '200DO') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 3), event_order = 15 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '100FA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 3), event_order = 16 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = 'S4X50SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 3), event_order = 17 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = 'S4X50MI') a);

update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 1), event_order = 101 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = 'M4X50SL') a);
delete from meeting_events where id > 0 and event_order > 100;
