-- Leega
-- 07/02/2017
-- 201702070011prod_program_fix_16276

-- select * from meeting_sessions ms where ms.meeting_id = 16276;
-- select et.code from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 order by ms.session_order, me.event_order;


update meeting_sessions ms set ms.swimming_pool_id = 13 where ms.id = 2046;
INSERT INTO meeting_sessions (id,session_order,meeting_id,swimming_pool_id,notes,description,user_id,lock_version,created_at,updated_at) VALUES  (2273,2,16276,(select ms.swimming_pool_id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 1),'','FINALI',2,0,CURDATE(),CURDATE());
INSERT INTO meeting_sessions (id,session_order,meeting_id,swimming_pool_id,notes,description,user_id,lock_version,created_at,updated_at) VALUES  (2274,3,16276,(select ms.swimming_pool_id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 1),'','FINALI',2,0,CURDATE(),CURDATE());
INSERT INTO meeting_sessions (id,session_order,meeting_id,swimming_pool_id,notes,description,user_id,lock_version,created_at,updated_at) VALUES  (2275,4,16276,(select ms.swimming_pool_id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 1),'','FINALI',2,0,CURDATE(),CURDATE());
INSERT INTO meeting_sessions (id,session_order,meeting_id,swimming_pool_id,notes,description,user_id,lock_version,created_at,updated_at) VALUES  (2276,5,16276,71,'','FINALI',2,0,CURDATE(),CURDATE());
INSERT INTO meeting_events (id,event_order,is_out_of_race,meeting_session_id,event_type_id,heat_type_id,user_id,lock_version,created_at,updated_at) values  (12108,22,0,(select t.id from meeting_sessions t where t.meeting_id = 16276 and t.session_order = 1),(select t.id from event_types t where t.code = '1500SL'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE());

--
-- aggiornamento orari sessioni per il meeting 16276
-- 
update meeting_sessions set day_part_type_id = (select id from day_part_types where code = 'M'), warm_up_time = '7:30:00', begin_time = '8:30:00', scheduled_date = '2017-01-28' where id > 0 and id = (select a.id from (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 1) a);
update meeting_sessions set day_part_type_id = (select id from day_part_types where code = 'P'), warm_up_time = '13:00:00', begin_time = '14:15:00', scheduled_date = '2017-01-28' where id > 0 and id = (select a.id from (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 2) a);
update meeting_sessions set day_part_type_id = (select id from day_part_types where code = 'M'), warm_up_time = '8:00:00', begin_time = '8:45:00', scheduled_date = '2017-01-29' where id > 0 and id = (select a.id from (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 3) a);
update meeting_sessions set day_part_type_id = (select id from day_part_types where code = 'P'), warm_up_time = '0:00:00', begin_time = '14:30:00', scheduled_date = '2017-01-29' where id > 0 and id = (select a.id from (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 4) a);
update meeting_sessions set day_part_type_id = (select id from day_part_types where code = 'P'), warm_up_time = '13:30:00', begin_time = '14:30:00', scheduled_date = '2017-02-05' where id > 0 and id = (select a.id from (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 5) a);

--
-- Aggiornamento programma gare per il meeting 16276
-- 
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 1), event_order = 1 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '400SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 1), event_order = 2 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '200DO') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 1), event_order = 3 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '400MI') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 1), event_order = 4 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '200RA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 1), event_order = 5 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '100FA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 2), event_order = 6 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '200SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 2), event_order = 7 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '100DO') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 2), event_order = 8 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '200FA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 2), event_order = 9 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '200MI') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 2), event_order = 10 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '1500SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 3), event_order = 11 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '800SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 3), event_order = 12 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '100SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 3), event_order = 13 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '100RA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 4), event_order = 14 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '50FA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 4), event_order = 15 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '50DO') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 4), event_order = 16 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '50RA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 4), event_order = 17 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '50SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 5), event_order = 18 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = '100MI') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 5), event_order = 19 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = 'S4X50SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 5), event_order = 20 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = 'M4X50MI') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 5), event_order = 21 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = 'S4X50MI') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16276 and ms.session_order = 5), event_order = 22 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16276 and et.code = 'M4X50SL') a);
