-- Leega
-- 18/01/2017
-- 201701180049prod_program_fix_16205

-- select * from meeting_sessions ms where ms.meeting_id = 16205;
-- select et.code from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 order by ms.session_order, me.event_order;
--
-- aggiornamento orari sessioni per il meeting 16205
-- 
update meeting_sessions set day_part_type_id = (select id from day_part_types where code = 'M'), warm_up_time = '13:30:00', begin_time = '14:30:00', scheduled_date = '2017-01-28' where id > 0 and id = (select a.id from (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 1) a);
update meeting_sessions set day_part_type_id = (select id from day_part_types where code = 'P'), warm_up_time = '7:30:00', begin_time = '8:30:00', scheduled_date = '2017-01-29' where id > 0 and id = (select a.id from (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 2) a);
update meeting_sessions set day_part_type_id = (select id from day_part_types where code = 'M'), warm_up_time = '13:30:00', begin_time = '14:30:00', scheduled_date = '2017-01-29' where id > 0 and id = (select a.id from (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 3) a);
delete from meeting_sessions where id > 0 and id = (select a.id from (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 4) a);

--
-- Aggiornamento programma gare per il meeting 16205
-- 
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 1), event_order = 1 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '100RA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 1), event_order = 2 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '50SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 1), event_order = 3 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '200FA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 1), event_order = 4 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '100MI') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 1), event_order = 5 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '100DO') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 2), event_order = 6 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '200RA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 2), event_order = 7 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '50DO') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 2), event_order = 8 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '200MI') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 2), event_order = 9 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '50FA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 2), event_order = 10 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '100SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 2), event_order = 11 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = 'M4X50MI') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 3), event_order = 12 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '200SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 3), event_order = 13 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '50RA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 3), event_order = 14 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '200DO') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 3), event_order = 15 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = '100FA') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 3), event_order = 16 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = 'S4X50SL') a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 16205 and ms.session_order = 3), event_order = 17 where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 16205 and et.code = 'S4X50MI') a);
