--
-- PassagesBatchUpdater: recorded from actions by [User: leega (Marco Ligabue) ID: 2]
-- 05 December 2016 14:18:52
-- Begin script
--

INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5824, 0, 52, 58, 83069, 2, 2, '2016-12-05 13:18:52', '2016-12-05 13:18:52', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 52, 58, 0, 474683, NULL, 28554, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5825, 0, 56, 58, 83069, 4, 2, '2016-12-05 13:18:53', '2016-12-05 13:18:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 49, 16, 0, 474683, NULL, 28554, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5826, 1, 2, 36, 83069, 6, 2, '2016-12-05 13:18:53', '2016-12-05 13:18:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 51, 52, 0, 474683, NULL, 28554, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5827, 1, 5, 14, 83069, 8, 2, '2016-12-05 13:18:53', '2016-12-05 13:18:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 56, 66, 0, 474683, NULL, 28554, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5828, 1, 5, 12, 83069, 10, 2, '2016-12-05 13:18:53', '2016-12-05 13:18:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 1, 78, 0, 474683, NULL, 28554, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5829, 1, 4, 7, 83069, 12, 2, '2016-12-05 13:18:53', '2016-12-05 13:18:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6, 5, 85, 0, 474683, NULL, 28554, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5830, 1, 4, 11, 83069, 14, 2, '2016-12-05 13:18:53', '2016-12-05 13:18:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7, 9, 96, 0, 474683, NULL, 28554, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5831, 1, 2, 84, 83069, 16, 2, '2016-12-05 13:18:53', '2016-12-05 13:18:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8, 12, 80, 0, 474683, NULL, 28554, 1);
