-- Leega
-- 27/10/2016
-- CSI Nuoto Ober Ferrari FIN affiliation & badges

-- Swimmers update
update swimmers set complete_name = 'NOBILI CESARE BRENNO', first_name = 'CESARE BRENNO' where id = 1514;
insert into swimmers 
(id, last_name, first_name, complete_name, year_of_birth, gender_type_id, user_id) 
values
(27445, 'NOVELLI', 'MICHELE', 'NOVELLI MICHELE', 1975, 1, 2);

--
-- Affiliazione CSI per FIN 162 team_affiliations
-- 
INSERT INTO team_affiliations (id,season_id,team_id,name,number,must_calculate_goggle_cup,user_id,lock_version,created_at,updated_at) VALUES 
(2451,162,1,'CSI NUOTO OBER FERRARI','EMI-001454',1,2,0,CURDATE(),CURDATE());

--
-- Dump dei dati per la tabella badges
-- 
INSERT INTO badges (id,season_id,team_id,swimmer_id,number,user_id,category_type_id,entry_time_type_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(55640,162,1,(select s.id from swimmers s where s.complete_name = 'ALLORO STEFANO' and s.year_of_birth = 1969),'EMI015613',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55641,162,1,(select s.id from swimmers s where s.complete_name = 'BARCHI FABIO' and s.year_of_birth = 1971),'EMI019649',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55642,162,1,(select s.id from swimmers s where s.complete_name = 'BENASSI SARA' and s.year_of_birth = 1985),'EMI028415',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55643,162,1,(select s.id from swimmers s where s.complete_name = 'BERTOZZI ORLANDO' and s.year_of_birth = 1968),'FIN068366',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55644,162,1,(select s.id from swimmers s where s.complete_name = 'BIANCHI ELENA' and s.year_of_birth = 1967),'EMI014277',2,(select t.id from category_types t where t.code = 'M50' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55645,162,1,(select s.id from swimmers s where s.complete_name = 'BONACINI MONICA' and s.year_of_birth = 1969),'EMI017971',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55646,162,1,(select s.id from swimmers s where s.complete_name = 'BRUNI SIMONE' and s.year_of_birth = 1978),'EMI026256',2,(select t.id from category_types t where t.code = 'M35' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55647,162,1,(select s.id from swimmers s where s.complete_name = 'BUDASSI VALENTINA' and s.year_of_birth = 1990),'MAR000774',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55648,162,1,(select s.id from swimmers s where s.complete_name = 'CANOVI GABRIELE' and s.year_of_birth = 1980),'EMI031097',2,(select t.id from category_types t where t.code = 'M35' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55649,162,1,(select s.id from swimmers s where s.complete_name = 'CANTONI SAMANTA' and s.year_of_birth = 1988),'EMI031096',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55650,162,1,(select s.id from swimmers s where s.complete_name = 'DEL RIO SIMONE' and s.year_of_birth = 1983),'EMI025730',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55651,162,1,(select s.id from swimmers s where s.complete_name = 'FERRARI ALESSIA' and s.year_of_birth = 1978),'EMI015589',2,(select t.id from category_types t where t.code = 'M35' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55652,162,1,(select s.id from swimmers s where s.complete_name = 'FERRI LUCA' and s.year_of_birth = 1965),'EMI026983',2,(select t.id from category_types t where t.code = 'M50' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55653,162,1,(select s.id from swimmers s where s.complete_name = 'FORMENTINI DAVIDE' and s.year_of_birth = 1988),'EMI004187',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55654,162,1,(select s.id from swimmers s where s.complete_name = 'FRANCESCHINI STEFANO' and s.year_of_birth = 1973),'EMI023179',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55655,162,1,(select s.id from swimmers s where s.complete_name = 'GIANSOLDATI MATTEO' and s.year_of_birth = 1989),'EMI021501',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55656,162,1,(select s.id from swimmers s where s.complete_name = 'LEONARDI ELISA' and s.year_of_birth = 1975),'EMI006827',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55657,162,1,(select s.id from swimmers s where s.complete_name = 'LEONCINI VALERIA' and s.year_of_birth = 1976),'EMI000904',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55658,162,1,(select s.id from swimmers s where s.complete_name = 'LIGABUE MARCO' and s.year_of_birth = 1971),'EMI014278',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55659,162,1,(select s.id from swimmers s where s.complete_name = 'NOBILI CESARE BRENNO' and s.year_of_birth = 1971),'EMI031098',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55660,162,1,(select s.id from swimmers s where s.complete_name = 'NOVELLI MICHELE' and s.year_of_birth = 1975),'EMI034244',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55661,162,1,(select s.id from swimmers s where s.complete_name = 'ORLANDINI IDO PIERALDO' and s.year_of_birth = 1957),'EMI015624',2,(select t.id from category_types t where t.code = 'M60' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55662,162,1,(select s.id from swimmers s where s.complete_name = 'PEZZI STEFANIA' and s.year_of_birth = 1981),'EMI029726',2,(select t.id from category_types t where t.code = 'M35' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55663,162,1,(select s.id from swimmers s where s.complete_name = 'ROSCA IOAN STELIAN' and s.year_of_birth = 1974),'FIN054100',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55664,162,1,(select s.id from swimmers s where s.complete_name = 'SESENA BARBARA' and s.year_of_birth = 1971),'EMI014276',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55665,162,1,(select s.id from swimmers s where s.complete_name = 'TARABINI RICCARDO' and s.year_of_birth = 1972),'EMI032255',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55666,162,1,(select s.id from swimmers s where s.complete_name = 'TOFFANETTI LAURA' and s.year_of_birth = 1973),'EMI015592',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55667,162,1,(select s.id from swimmers s where s.complete_name = 'TOSI VALENTINA' and s.year_of_birth = 1989),'EMI027861',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55668,162,1,(select s.id from swimmers s where s.complete_name = 'VALCAVI LUCA' and s.year_of_birth = 1988),'FIN055696',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55669,162,1,(select s.id from swimmers s where s.complete_name = 'VEZZANI GIORGIA' and s.year_of_birth = 1995),'EMI032423',2,(select t.id from category_types t where t.code = 'U25' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE()),
(55670,162,1,(select s.id from swimmers s where s.complete_name = 'ZULIANI MATTEO' and s.year_of_birth = 1992),'EMI005301',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 162),(select t.id from entry_time_types t where t.code = 'G'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 162),0,CURDATE(),CURDATE());
