--
-- PassagesBatchUpdater: recorded from actions by [User: leega (Marco Ligabue) ID: 2]
-- 19 December 2016 14:11:46
-- Begin script
--

INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6091, 0, 39, 85, 90658, 2, 2, '2016-12-19 13:11:46', '2016-12-19 13:11:46', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 39, 85, 0, 516182, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6092, 0, 43, 88, 90658, 4, 2, '2016-12-19 13:11:47', '2016-12-19 13:11:47', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 23, 73, 0, 516182, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6093, 0, 45, 69, 90658, 6, 2, '2016-12-19 13:11:47', '2016-12-19 13:11:47', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 9, 42, 0, 516182, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6094, 0, 46, 15, 90658, 8, 2, '2016-12-19 13:11:47', '2016-12-19 13:11:47', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 55, 57, 0, 516182, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6095, 0, 46, 84, 90658, 10, 2, '2016-12-19 13:11:48', '2016-12-19 13:11:48', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 42, 41, 0, 516182, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6096, 0, 48, 29, 90658, 12, 2, '2016-12-19 13:11:48', '2016-12-19 13:11:48', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, 30, 70, 0, 516182, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6097, 0, 48, 65, 90658, 14, 2, '2016-12-19 13:11:49', '2016-12-19 13:11:49', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 19, 35, 0, 516182, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6098, 0, 48, 47, 90658, 16, 2, '2016-12-19 13:11:49', '2016-12-19 13:11:49', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6, 7, 82, 0, 516182, NULL, 138, 1);
