--
-- PassagesBatchUpdater: recorded from actions by [User: leega (Marco Ligabue) ID: 2]
-- 05 December 2016 14:21:32
-- Begin script
--

UPDATE `passages`
  SET `user_id`=2, `minutes`=0, `seconds`=52, `hundreds`=58, `minutes_from_start`=0, `seconds_from_start`=52, `hundreds_from_start`=58
  WHERE (`id`=5824);
UPDATE `passages`
  SET `user_id`=2, `minutes`=0, `seconds`=56, `hundreds`=58, `minutes_from_start`=1, `seconds_from_start`=49, `hundreds_from_start`=16
  WHERE (`id`=5825);
UPDATE `passages`
  SET `user_id`=2, `minutes`=1, `seconds`=2, `hundreds`=36, `minutes_from_start`=2, `seconds_from_start`=51, `hundreds_from_start`=52
  WHERE (`id`=5826);
UPDATE `passages`
  SET `user_id`=2, `minutes`=1, `seconds`=5, `hundreds`=14, `minutes_from_start`=3, `seconds_from_start`=56, `hundreds_from_start`=66
  WHERE (`id`=5827);
UPDATE `passages`
  SET `user_id`=2, `minutes`=1, `seconds`=5, `hundreds`=12, `minutes_from_start`=5, `seconds_from_start`=1, `hundreds_from_start`=78
  WHERE (`id`=5828);
UPDATE `passages`
  SET `user_id`=2, `minutes`=1, `seconds`=4, `hundreds`=7, `minutes_from_start`=6, `seconds_from_start`=5, `hundreds_from_start`=85
  WHERE (`id`=5829);
UPDATE `passages`
  SET `user_id`=2, `minutes`=1, `seconds`=4, `hundreds`=11, `minutes_from_start`=7, `seconds_from_start`=9, `hundreds_from_start`=96
  WHERE (`id`=5830);
UPDATE `passages`
  SET `user_id`=2, `minutes`=1, `seconds`=2, `hundreds`=84, `minutes_from_start`=8, `seconds_from_start`=12, `hundreds_from_start`=80
  WHERE (`id`=5831);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5832, 0, 39, 59, 83131, 2, 2, '2016-12-05 13:21:33', '2016-12-05 13:21:33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 39, 59, 0, 474578, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5833, 0, 45, 7, 83131, 4, 2, '2016-12-05 13:21:33', '2016-12-05 13:21:33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 24, 66, 0, 474578, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5834, 0, 47, 1, 83131, 6, 2, '2016-12-05 13:21:33', '2016-12-05 13:21:33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 11, 67, 0, 474578, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5835, 0, 48, 18, 83131, 8, 2, '2016-12-05 13:21:33', '2016-12-05 13:21:33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 59, 85, 0, 474578, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5836, 0, 48, 67, 83131, 10, 2, '2016-12-05 13:21:33', '2016-12-05 13:21:33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 48, 52, 0, 474578, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5837, 0, 49, 20, 83131, 12, 2, '2016-12-05 13:21:33', '2016-12-05 13:21:33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, 37, 72, 0, 474578, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5838, 0, 49, 7, 83131, 14, 2, '2016-12-05 13:21:34', '2016-12-05 13:21:34', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 26, 79, 0, 474578, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5839, 0, 47, 11, 83131, 16, 2, '2016-12-05 13:21:34', '2016-12-05 13:21:34', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6, 13, 90, 0, 474578, NULL, 138, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5840, 0, 36, 76, 83097, 2, 2, '2016-12-05 13:21:34', '2016-12-05 13:21:34', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 36, 76, 0, 474611, NULL, 1843, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5841, 0, 40, 37, 83097, 4, 2, '2016-12-05 13:21:34', '2016-12-05 13:21:34', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 17, 13, 0, 474611, NULL, 1843, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5842, 0, 41, 42, 83097, 6, 2, '2016-12-05 13:21:34', '2016-12-05 13:21:34', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 58, 55, 0, 474611, NULL, 1843, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5843, 0, 43, 3, 83097, 8, 2, '2016-12-05 13:21:34', '2016-12-05 13:21:34', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 41, 58, 0, 474611, NULL, 1843, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5844, 0, 43, 49, 83097, 10, 2, '2016-12-05 13:21:34', '2016-12-05 13:21:34', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 25, 7, 0, 474611, NULL, 1843, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5845, 0, 43, 59, 83097, 12, 2, '2016-12-05 13:21:34', '2016-12-05 13:21:34', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, 8, 66, 0, 474611, NULL, 1843, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5846, 0, 44, 2, 83097, 14, 2, '2016-12-05 13:21:35', '2016-12-05 13:21:35', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, 52, 68, 0, 474611, NULL, 1843, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5847, 0, 43, 2, 83097, 16, 2, '2016-12-05 13:21:35', '2016-12-05 13:21:35', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 35, 70, 0, 474611, NULL, 1843, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5848, 0, 36, 40, 83069, 2, 2, '2016-12-05 13:21:35', '2016-12-05 13:21:35', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 36, 40, 0, 474591, NULL, 1788, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5849, 0, 40, 11, 83069, 4, 2, '2016-12-05 13:21:35', '2016-12-05 13:21:35', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 16, 51, 0, 474591, NULL, 1788, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5850, 0, 42, 96, 83069, 6, 2, '2016-12-05 13:21:35', '2016-12-05 13:21:35', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 59, 47, 0, 474591, NULL, 1788, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5851, 0, 41, 97, 83069, 8, 2, '2016-12-05 13:21:35', '2016-12-05 13:21:35', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 41, 44, 0, 474591, NULL, 1788, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5852, 0, 42, 71, 83069, 10, 2, '2016-12-05 13:21:35', '2016-12-05 13:21:35', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 24, 15, 0, 474591, NULL, 1788, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5853, 0, 42, 82, 83069, 12, 2, '2016-12-05 13:21:35', '2016-12-05 13:21:35', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, 6, 97, 0, 474591, NULL, 1788, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5854, 0, 41, 4, 83069, 14, 2, '2016-12-05 13:21:36', '2016-12-05 13:21:36', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, 48, 1, 0, 474591, NULL, 1788, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5855, 0, 38, 69, 83069, 16, 2, '2016-12-05 13:21:36', '2016-12-05 13:21:36', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 26, 70, 0, 474591, NULL, 1788, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5856, 0, 33, 12, 83066, 2, 2, '2016-12-05 13:21:36', '2016-12-05 13:21:36', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 33, 12, 0, 474590, NULL, 1841, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5857, 0, 36, 83, 83066, 4, 2, '2016-12-05 13:21:36', '2016-12-05 13:21:36', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 9, 95, 0, 474590, NULL, 1841, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5858, 0, 38, 6, 83066, 6, 2, '2016-12-05 13:21:36', '2016-12-05 13:21:36', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 48, 1, 0, 474590, NULL, 1841, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5859, 0, 39, 1, 83066, 8, 2, '2016-12-05 13:21:36', '2016-12-05 13:21:36', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 27, 2, 0, 474590, NULL, 1841, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5860, 0, 39, 87, 83066, 10, 2, '2016-12-05 13:21:36', '2016-12-05 13:21:36', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 6, 89, 0, 474590, NULL, 1841, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5861, 0, 41, 28, 83066, 12, 2, '2016-12-05 13:21:36', '2016-12-05 13:21:36', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 48, 17, 0, 474590, NULL, 1841, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5862, 0, 39, 26, 83066, 14, 2, '2016-12-05 13:21:37', '2016-12-05 13:21:37', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, 27, 43, 0, 474590, NULL, 1841, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5863, 0, 39, 7, 83066, 16, 2, '2016-12-05 13:21:37', '2016-12-05 13:21:37', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 6, 50, 0, 474590, NULL, 1841, 1);
