--
-- PassagesBatchUpdater: recorded from actions by [User: leega (Marco Ligabue) ID: 2]
-- 30 January 2017 13:55:52
-- Begin script
--

INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6347, 0, 40, 37, 94664, 2, 2, '2017-01-30 12:55:53', '2017-01-30 12:55:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 40, 37, 0, 534806, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6348, 0, 46, 80, 94664, 4, 2, '2017-01-30 12:55:53', '2017-01-30 12:55:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 27, 17, 0, 534806, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6349, 0, 47, 57, 94664, 6, 2, '2017-01-30 12:55:53', '2017-01-30 12:55:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 14, 74, 0, 534806, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6350, 0, 47, 33, 94664, 8, 2, '2017-01-30 12:55:53', '2017-01-30 12:55:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 2, 7, 0, 534806, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6351, 0, 36, 53, 94581, 2, 2, '2017-01-30 12:55:53', '2017-01-30 12:55:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 36, 53, 0, 534400, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6352, 0, 40, 18, 94581, 4, 2, '2017-01-30 12:55:54', '2017-01-30 12:55:54', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 16, 71, 0, 534400, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6353, 0, 29, 71, 94595, 2, 2, '2017-01-30 12:55:54', '2017-01-30 12:55:54', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 29, 71, 0, 534567, NULL, 1227, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6354, 0, 33, 74, 94595, 4, 2, '2017-01-30 12:55:54', '2017-01-30 12:55:54', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 3, 45, 0, 534567, NULL, 1227, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6355, 0, 39, 47, 94673, 2, 2, '2017-01-30 12:55:54', '2017-01-30 12:55:54', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 39, 47, 0, 534842, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6356, 0, 42, 35, 94673, 4, 2, '2017-01-30 12:55:55', '2017-01-30 12:55:55', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 21, 82, 0, 534842, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6357, 0, 44, 96, 94673, 6, 2, '2017-01-30 12:55:55', '2017-01-30 12:55:55', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 6, 78, 0, 534842, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6358, 0, 43, 78, 94673, 8, 2, '2017-01-30 12:55:55', '2017-01-30 12:55:55', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 50, 56, 0, 534842, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6359, 0, 35, 77, 94686, 2, 2, '2017-01-30 12:55:55', '2017-01-30 12:55:55', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 35, 77, 0, 534928, NULL, 1016, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6360, 0, 40, 45, 94686, 4, 2, '2017-01-30 12:55:55', '2017-01-30 12:55:55', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 16, 22, 0, 534928, NULL, 1016, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6361, 0, 43, 36, 94686, 6, 2, '2017-01-30 12:55:56', '2017-01-30 12:55:56', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 59, 58, 0, 534928, NULL, 1016, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6362, 0, 44, 25, 94686, 8, 2, '2017-01-30 12:55:56', '2017-01-30 12:55:56', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 43, 83, 0, 534928, NULL, 1016, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6363, 0, 32, 44, 94687, 2, 2, '2017-01-30 12:55:56', '2017-01-30 12:55:56', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 32, 44, 0, 534937, NULL, 1227, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6364, 0, 35, 21, 94687, 4, 2, '2017-01-30 12:55:56', '2017-01-30 12:55:56', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 7, 65, 0, 534937, NULL, 1227, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6365, 0, 38, 3, 94687, 6, 2, '2017-01-30 12:55:56', '2017-01-30 12:55:56', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 45, 68, 0, 534937, NULL, 1227, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6366, 0, 37, 86, 94687, 8, 2, '2017-01-30 12:55:56', '2017-01-30 12:55:56', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 23, 54, 0, 534937, NULL, 1227, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6367, 0, 30, 16, 94683, 2, 2, '2017-01-30 12:55:57', '2017-01-30 12:55:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 30, 16, 0, 534881, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6368, 0, 33, 45, 94683, 4, 2, '2017-01-30 12:55:57', '2017-01-30 12:55:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 3, 61, 0, 534881, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6369, 0, 35, 44, 94683, 6, 2, '2017-01-30 12:55:57', '2017-01-30 12:55:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 39, 5, 0, 534881, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6370, 0, 36, 26, 94683, 8, 2, '2017-01-30 12:55:57', '2017-01-30 12:55:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 15, 31, 0, 534881, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6371, 0, 19, 29, 94744, 1, 2, '2017-01-30 12:55:57', '2017-01-30 12:55:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 19, 29, 0, 535280, NULL, 1016, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6372, 0, 22, 86, 94744, 2, 2, '2017-01-30 12:55:57', '2017-01-30 12:55:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 42, 15, 0, 535280, NULL, 1016, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6373, 0, 17, 16, 94742, 1, 2, '2017-01-30 12:55:58', '2017-01-30 12:55:58', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 17, 16, 0, 535256, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (6374, 0, 19, 79, 94742, 2, 2, '2017-01-30 12:55:58', '2017-01-30 12:55:58', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 36, 95, 0, 535256, NULL, 1409, 1);
