-- Leega
-- 22/01/2017
-- CSIProva1 realy swimmers

-- Fix missing badges (swimmers who partecipates only for relays)
-- GAVANELLI CRISTIAN M35 (87) - Savena (11)
INSERT INTO badges 
(id,season_id,team_id,swimmer_id,number,user_id,category_type_id,entry_time_type_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(76555,161,11,87,'?',2,(select t.id from category_types t where t.code = 'M35' and t.season_id = 161),null,(select ta.id from team_affiliations ta where ta.team_id = 11 and ta.season_id = 161),0,CURDATE(),CURDATE());
-- BONARETTI VILLIAM M55 (27323) - Eden (826)
INSERT INTO badges 
(id,season_id,team_id,swimmer_id,number,user_id,category_type_id,entry_time_type_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(76556,161,826,27323,'?',2,(select t.id from category_types t where t.code = 'M55' and t.season_id = 161),null,(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 161),0,CURDATE(),CURDATE());

-- Fix missing csiprova2 swimmers (only one remains)
-- GAVANELLI CRISTIAN
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (379,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'GAVANELLI CRISTIAN'),21986,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'GAVANELLI CRISTIAN'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
-- BONARETTI VILLIAM
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (454,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'BONARETTI VILLIAM'),22005,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'BONARETTI VILLIAM'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());

-- CSIProva1 relay swimmers
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (461,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'MONTICELLI ANNA'),20911,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'MONTICELLI ANNA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (462,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'NASI NICOLE'),20911,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'NASI NICOLE'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (463,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'PESARE REBECCA'),20911,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'PESARE REBECCA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (464,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BUDASSI VALENTINA'),20911,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BUDASSI VALENTINA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (465,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'PARMIGIANI SILVIA'),20912,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'PARMIGIANI SILVIA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (466,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'PATERLINI GRETA'),20912,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'PATERLINI GRETA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (467,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'TAGLIATI GENNY'),20912,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'TAGLIATI GENNY'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (468,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'MANICARDI VERONICA'),20912,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'MANICARDI VERONICA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (469,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'LORENZOTTI VALENTINA'),20913,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'LORENZOTTI VALENTINA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (470,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'FRANCANO GABRIELLA'),20913,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'FRANCANO GABRIELLA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (471,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'VITALI ALESSANDRA'),20913,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'VITALI ALESSANDRA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (472,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'SALVATI GLORIA'),20913,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'SALVATI GLORIA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (473,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'INCERTI DELMONTE CHIARA'),20914,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'INCERTI DELMONTE CHIARA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (474,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'OGNIBENE GLORIA'),20914,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'OGNIBENE GLORIA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (475,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'ROTA CAMILLA'),20914,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'ROTA CAMILLA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (476,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'INCERTI DELMONTE ELISA'),20914,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'INCERTI DELMONTE ELISA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (477,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'BENASSI SARA'),20915,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'BENASSI SARA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (478,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'ZANNINI GIORGIA'),20915,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'ZANNINI GIORGIA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (479,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'TOSI VALENTINA'),20915,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'TOSI VALENTINA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (480,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'CANTONI SAMANTA'),20915,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'CANTONI SAMANTA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (481,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'ROMANINI SILVIA'),20916,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'ROMANINI SILVIA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (482,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'FRANCHI CHIARA'),20916,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'FRANCHI CHIARA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (483,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'FAVARON SARA'),20916,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'FAVARON SARA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (484,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'MARANDO SILVIA'),20916,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'MARANDO SILVIA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());





INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (485,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'MARCHETTA LEONARDO'),20917,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'MARCHETTA LEONARDO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (486,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'RUBINO FRANCESCO'),20917,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'RUBINO FRANCESCO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (487,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'D''AMICO ELPIDIO'),20917,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'D''AMICO ELPIDIO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (488,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'BAZZURRI LUIGI'),20917,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 21 and s.complete_name = 'BAZZURRI LUIGI'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (489,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'ZIRONI MATTEO'),20918,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'ZIRONI MATTEO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (490,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'DAVOLIO FEDERICO'),20918,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'DAVOLIO FEDERICO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (491,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'CATELLANI LUCA'),20918,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'CATELLANI LUCA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (492,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'GOZZI FABIO'),20918,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'GOZZI FABIO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());

INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (494,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'PALLADINO FRANCESCO'),20919,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'PALLADINO FRANCESCO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());

INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (496,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'FREDDI MATTEO'),20919,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'FREDDI MATTEO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (497,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'BERTOCCHI FABIO'),20920,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'BERTOCCHI FABIO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (498,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'DEL RIO SIMONE'),20920,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'DEL RIO SIMONE'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (499,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'GIANSOLDATI MATTEO'),20920,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'GIANSOLDATI MATTEO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (500,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'GHIRARDELLI CRISTIAN'),20920,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 35 and s.complete_name = 'GHIRARDELLI CRISTIAN'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (501,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1000 and s.complete_name = 'LEONI MARCO'),20921,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1000 and s.complete_name = 'LEONI MARCO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (502,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1000 and s.complete_name = 'MORSIANI FEDERICO'),20921,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1000 and s.complete_name = 'MORSIANI FEDERICO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (503,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1000 and s.complete_name = 'FRANCESCHINI FEDERICO'),20921,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1000 and s.complete_name = 'FRANCESCHINI FEDERICO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (504,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1000 and s.complete_name = 'BERTANI DANIELE'),20921,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1000 and s.complete_name = 'BERTANI DANIELE'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (505,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'ROSI EMANUELE'),20922,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'ROSI EMANUELE'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (506,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'GALIANO DAVIDE'),20922,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'GALIANO DAVIDE'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (507,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'BRAMBILLA MARCO'),20922,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'BRAMBILLA MARCO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (508,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'GANDOLFI SARA'),20922,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'GANDOLFI SARA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (509,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'DEMURU MIKHAIL'),20923,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'DEMURU MIKHAIL'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (510,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BURANI PIETRO'),20923,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BURANI PIETRO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (511,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BRUNI SIMONE'),20923,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BRUNI SIMONE'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (512,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'FORMENTINI DAVIDE'),20923,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'FORMENTINI DAVIDE'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (513,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'FRANZINI CESAR DAVID'),20924,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'FRANZINI CESAR DAVID'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (514,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'ZINANI FRANCESCO'),20924,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'ZINANI FRANCESCO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (515,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'VEZZANI GIACOMO'),20924,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'VEZZANI GIACOMO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (516,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'BATTINI ELIA'),20924,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'BATTINI ELIA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (517,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 290 and s.complete_name = 'BIOLCHINI DANIEL'),20925,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 290 and s.complete_name = 'BIOLCHINI DANIEL'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (518,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 290 and s.complete_name = 'MATARAZZO GABRIELE'),20925,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 290 and s.complete_name = 'MATARAZZO GABRIELE'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (519,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 290 and s.complete_name = 'POZZI FEDERICO'),20925,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 290 and s.complete_name = 'POZZI FEDERICO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (520,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 290 and s.complete_name = 'CUFFIANI PAOLO'),20925,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 290 and s.complete_name = 'CUFFIANI PAOLO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());




INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (521,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'ARMANI VERONICA'),20926,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'ARMANI VERONICA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (522,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'FERRARI ALESSIA'),20926,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'FERRARI ALESSIA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (523,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'PEZZI STEFANIA'),20926,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'PEZZI STEFANIA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (524,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'LEONCINI VALERIA'),20926,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'LEONCINI VALERIA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (525,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'MARTINELLI CARLOTTA'),20927,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'MARTINELLI CARLOTTA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (526,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'CASANOVA FEDERICA'),20927,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'CASANOVA FEDERICA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (527,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'GANDOLFI ANNA'),20927,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'GANDOLFI ANNA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (528,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'CARRI LISA'),20927,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'CARRI LISA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (529,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'CASAROSA PAOLA'),20928,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'CASAROSA PAOLA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (530,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'PEZZOTTA MANUELA'),20928,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'PEZZOTTA MANUELA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (531,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'GHEDINI GIULIA'),20928,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'GHEDINI GIULIA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (532,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'PARADISI VALENTINA'),20928,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'PARADISI VALENTINA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (533,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'COLAZZO ELENA'),20929,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'COLAZZO ELENA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (534,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'BAGNACANI ALESSANDRA'),20929,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'BAGNACANI ALESSANDRA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (535,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'VANTAGGIO MARTINA'),20929,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'VANTAGGIO MARTINA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (536,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'BEVINI PAOLA'),20929,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'BEVINI PAOLA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());





INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (537,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'NAGY MARCO'),20930,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'NAGY MARCO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (538,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'COIRO FEDERICO'),20930,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'COIRO FEDERICO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (539,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'GRADI ANDREA'),20930,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'GRADI ANDREA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (540,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'BALLIN LORENZO'),20930,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'BALLIN LORENZO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (541,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'CALZOLARI MARCO'),20931,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'CALZOLARI MARCO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (542,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'CUCCONI FRANCESCO'),20931,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'CUCCONI FRANCESCO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (543,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'LEONI ALESSANDRO'),20931,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'LEONI ALESSANDRO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (544,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'PASTORELLI GABRIELE'),20931,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'PASTORELLI GABRIELE'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (545,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'STORCHI LORENZO'),20932,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'STORCHI LORENZO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (546,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'RONZONI ALESSANDRO'),20932,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'RONZONI ALESSANDRO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (547,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'VALCAVI LUCA'),20932,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'VALCAVI LUCA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (548,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BERTANI STEFANO'),20932,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BERTANI STEFANO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (549,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'ZAGATTI ALESSANDRO'),20933,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'ZAGATTI ALESSANDRO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (550,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'FRATTI DAVIDE'),20933,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'FRATTI DAVIDE'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (551,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'INCERTI ALESSANDRO'),20933,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'INCERTI ALESSANDRO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (552,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'MONTI MARCO'),20933,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'MONTI MARCO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (553,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'FERRARI CLAUDIO'),20934,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'FERRARI CLAUDIO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (554,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'GUTIERREZ MELENDEZ HARVIS ORLA'),20934,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'GUTIERREZ MELENDEZ HARVIS ORLA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (555,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'CAMPANI GIOVANNI'),20934,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'CAMPANI GIOVANNI'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (556,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'LIGABUE ANDREA'),20934,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'LIGABUE ANDREA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (557,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'FAVA ANDREA'),20935,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'FAVA ANDREA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (558,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'MONTI GABRIELE'),20935,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'MONTI GABRIELE'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (559,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'PANIZZI GIACOMO'),20935,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'PANIZZI GIACOMO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (560,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'FURLOTTI CHRISTIAN'),20935,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'FURLOTTI CHRISTIAN'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());




INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (561,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'GAITI GIULIANA'),20936,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'GAITI GIULIANA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (562,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'CROTTI MILENA'),20936,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'CROTTI MILENA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (563,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'BORGHI DONATELLA'),20936,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'BORGHI DONATELLA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (564,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'BERTOLINI MANUELA'),20936,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 10 and s.complete_name = 'BERTOLINI MANUELA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (565,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'VEZZANI SARA'),20937,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'VEZZANI SARA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (566,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'SANTINI FEDERICA'),20937,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'SANTINI FEDERICA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (567,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'BULGARELLI CRISTIANA'),20937,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'BULGARELLI CRISTIANA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (568,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'PO ILARIA'),20937,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'PO ILARIA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (569,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'VALTUENA MARTINEZ SILVIA'),20938,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'VALTUENA MARTINEZ SILVIA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (570,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'VANNUCCI PAOLA'),20938,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'VANNUCCI PAOLA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (571,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'BRAGHIROLI ELISA'),20938,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'BRAGHIROLI ELISA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (572,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'MOLINARICH NORMA'),20938,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'MOLINARICH NORMA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (573,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'SESENA BARBARA'),20939,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'SESENA BARBARA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (574,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BIANCHI ELENA'),20939,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BIANCHI ELENA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (575,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BONACINI MONICA'),20939,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BONACINI MONICA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (576,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BERNARDELLI NICLA'),20939,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BERNARDELLI NICLA'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());



INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (577,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'FERRARI FRANCESCO'),20940,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'FERRARI FRANCESCO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (578,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'ALLORO STEFANO'),20940,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'ALLORO STEFANO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (579,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'LIGABUE MARCO'),20940,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'LIGABUE MARCO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (580,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BERTOZZI ORLANDO'),20940,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'BERTOZZI ORLANDO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (581,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'OLIVIERI SIMONE'),20941,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'OLIVIERI SIMONE'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (582,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'CROTTI MASSIMILIANO'),20941,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'CROTTI MASSIMILIANO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (583,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'BULGARELLI LUCA'),20941,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'BULGARELLI LUCA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (584,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'PIERANTONI MASSIMO'),20941,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'PIERANTONI MASSIMO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (585,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'ORLANDINI EDO'),20942,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'ORLANDINI EDO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (586,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'DAVOLIO MASSIMO'),20942,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'DAVOLIO MASSIMO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (587,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'FOSSILE ROBERTO'),20942,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'FOSSILE ROBERTO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (588,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'REGNANI FEDERICO'),20942,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 14 and s.complete_name = 'REGNANI FEDERICO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (589,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'GAVANELLI CRISTIAN'),20943,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'GAVANELLI CRISTIAN'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (590,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'SERRA ANDREA'),20943,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'SERRA ANDREA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (591,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'PALESTINI STEFANO'),20943,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'PALESTINI STEFANO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (592,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'FABBRI STEFANO'),20943,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 11 and s.complete_name = 'FABBRI STEFANO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (593,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'BERNARDELLI FEDERICO'),20944,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'BERNARDELLI FEDERICO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (594,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'FORNETTI DAVIDE'),20944,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'FORNETTI DAVIDE'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (595,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'FRIGNANI DANIELE'),20944,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'FRIGNANI DANIELE'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (596,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'PIVETTI MAXIMILIANO'),20944,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 5 and s.complete_name = 'PIVETTI MAXIMILIANO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (597,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'MESSORI ANDREA'),20945,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'MESSORI ANDREA'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (598,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'LIBBRA STEFANO'),20945,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'LIBBRA STEFANO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (599,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'CARBONI PAOLO'),20945,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'CARBONI PAOLO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (600,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'PRAMPOLINI STEFANO'),20945,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'PRAMPOLINI STEFANO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (601,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'STROZZI PIERANTONIO'),20946,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'STROZZI PIERANTONIO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (602,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'CILLONI IVANO'),20946,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'CILLONI IVANO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (603,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'ORLANDINI IDO PIERALDO'),20946,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'ORLANDINI IDO PIERALDO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (604,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'FRANCESCHINI STEFANO'),20946,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 1 and s.complete_name = 'FRANCESCHINI STEFANO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (605,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'MONTICELLI FABIO'),20947,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'MONTICELLI FABIO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (606,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'ZAMBELLI IVANO'),20947,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'ZAMBELLI IVANO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (607,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'CANZIAN LUCA'),20947,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'CANZIAN LUCA'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (608,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'GHIDONI MASSIMO'),20947,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 18 and s.complete_name = 'GHIDONI MASSIMO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (609,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'INCERTI PAOLO'),20948,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'INCERTI PAOLO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (610,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'OGNIBENE ANDREA'),20948,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'OGNIBENE ANDREA'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (611,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'MARGINI LEONARDO'),20948,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'MARGINI LEONARDO'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (612,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'CODELUPPI FRANCO'),20948,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 826 and s.complete_name = 'CODELUPPI FRANCO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (613,1,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'TONI MARCO'),20949,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'TONI MARCO'),(select t.id from stroke_types t where t.code = 'DO'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (614,2,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'VERZANI MASSIMO'),20949,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'VERZANI MASSIMO'),(select t.id from stroke_types t where t.code = 'RA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (615,3,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'DONATACCI GIUSEPPE'),20949,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'DONATACCI GIUSEPPE'),(select t.id from stroke_types t where t.code = 'FA'),2,0,curdate(),curdate());
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,meeting_relay_result_id,badge_id,stroke_type_id,user_id,lock_version,created_at,updated_at) values (616,4,(select s.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'REBUCCI GIORGIO'),20949,(select b.id from swimmers s join badges b on b.swimmer_id = s.id where b.season_id = 161 and b.team_id = 4 and s.complete_name = 'REBUCCI GIORGIO'),(select t.id from stroke_types t where t.code = 'SL'),2,0,curdate(),curdate());

--
-- Integrazione manuale dati staffette 16101 per la tabella meeting_relay_swimmers
-- 
-- I dati devono esser già stati acquisiti con anche gli swimmers
UPDATE meeting_relay_swimmers SET minutes = 0, seconds = 33, hundreds = 26 WHERE id > 0 and id = (select a.id from (select mrs.id from meeting_relay_swimmers mrs join meeting_relay_results mrr on mrr.id = mrs.meeting_relay_result_id join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id  join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id join swimmers s on s.id = mrs.swimmer_id where ms.meeting_id = 16101 and  s.complete_name = 'STORCHI LORENZO' and et.code = 'S4X50MI') a);
UPDATE meeting_relay_swimmers SET minutes = 0, seconds = 39, hundreds = 29 WHERE id > 0 and id = (select a.id from (select mrs.id from meeting_relay_swimmers mrs join meeting_relay_results mrr on mrr.id = mrs.meeting_relay_result_id join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id  join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id join swimmers s on s.id = mrs.swimmer_id where ms.meeting_id = 16101 and  s.complete_name = 'RONZONI ALESSANDRO' and et.code = 'S4X50MI') a);
UPDATE meeting_relay_swimmers SET minutes = 0, seconds = 29, hundreds = 4 WHERE id > 0 and id = (select a.id from (select mrs.id from meeting_relay_swimmers mrs join meeting_relay_results mrr on mrr.id = mrs.meeting_relay_result_id join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id  join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id join swimmers s on s.id = mrs.swimmer_id where ms.meeting_id = 16101 and  s.complete_name = 'VALCAVI LUCA' and et.code = 'S4X50MI') a);
UPDATE meeting_relay_swimmers SET minutes = 0, seconds = 30, hundreds = 1 WHERE id > 0 and id = (select a.id from (select mrs.id from meeting_relay_swimmers mrs join meeting_relay_results mrr on mrr.id = mrs.meeting_relay_result_id join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id  join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id join swimmers s on s.id = mrs.swimmer_id where ms.meeting_id = 16101 and  s.complete_name = 'BERTANI STEFANO' and et.code = 'S4X50MI') a);
UPDATE meeting_relay_swimmers SET minutes = 0, seconds = 36, hundreds = 73 WHERE id > 0 and id = (select a.id from (select mrs.id from meeting_relay_swimmers mrs join meeting_relay_results mrr on mrr.id = mrs.meeting_relay_result_id join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id  join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id join swimmers s on s.id = mrs.swimmer_id where ms.meeting_id = 16101 and  s.complete_name = 'FERRARI FRANCESCO' and et.code = 'S4X50MI') a);
UPDATE meeting_relay_swimmers SET minutes = 0, seconds = 36, hundreds = 27 WHERE id > 0 and id = (select a.id from (select mrs.id from meeting_relay_swimmers mrs join meeting_relay_results mrr on mrr.id = mrs.meeting_relay_result_id join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id  join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id join swimmers s on s.id = mrs.swimmer_id where ms.meeting_id = 16101 and  s.complete_name = 'ALLORO STEFANO' and et.code = 'S4X50MI') a);
UPDATE meeting_relay_swimmers SET minutes = 0, seconds = 31, hundreds = 50 WHERE id > 0 and id = (select a.id from (select mrs.id from meeting_relay_swimmers mrs join meeting_relay_results mrr on mrr.id = mrs.meeting_relay_result_id join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id  join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id join swimmers s on s.id = mrs.swimmer_id where ms.meeting_id = 16101 and  s.complete_name = 'LIGABUE MARCO' and et.code = 'S4X50MI') a);
UPDATE meeting_relay_swimmers SET minutes = 0, seconds = 28, hundreds = 60 WHERE id > 0 and id = (select a.id from (select mrs.id from meeting_relay_swimmers mrs join meeting_relay_results mrr on mrr.id = mrs.meeting_relay_result_id join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id  join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id join swimmers s on s.id = mrs.swimmer_id where ms.meeting_id = 16101 and  s.complete_name = 'BERTOZZI ORLANDO' and et.code = 'S4X50MI') a);
UPDATE meeting_relay_swimmers SET minutes = 0, seconds = 44, hundreds = 15 WHERE id > 0 and id = (select a.id from (select mrs.id from meeting_relay_swimmers mrs join meeting_relay_results mrr on mrr.id = mrs.meeting_relay_result_id join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id  join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id join swimmers s on s.id = mrs.swimmer_id where ms.meeting_id = 16101 and  s.complete_name = 'STROZZI PIERANTONIO' and et.code = 'S4X50MI') a);
UPDATE meeting_relay_swimmers SET minutes = 0, seconds = 42, hundreds = 77 WHERE id > 0 and id = (select a.id from (select mrs.id from meeting_relay_swimmers mrs join meeting_relay_results mrr on mrr.id = mrs.meeting_relay_result_id join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id  join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id join swimmers s on s.id = mrs.swimmer_id where ms.meeting_id = 16101 and  s.complete_name = 'CILLONI IVANO' and et.code = 'S4X50MI') a);
UPDATE meeting_relay_swimmers SET minutes = 0, seconds = 37, hundreds = 70 WHERE id > 0 and id = (select a.id from (select mrs.id from meeting_relay_swimmers mrs join meeting_relay_results mrr on mrr.id = mrs.meeting_relay_result_id join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id  join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id join swimmers s on s.id = mrs.swimmer_id where ms.meeting_id = 16101 and  s.complete_name = 'ORLANDINI IDO PIERALDO' and et.code = 'S4X50MI') a);
UPDATE meeting_relay_swimmers SET minutes = 0, seconds = 32, hundreds = 38 WHERE id > 0 and id = (select a.id from (select mrs.id from meeting_relay_swimmers mrs join meeting_relay_results mrr on mrr.id = mrs.meeting_relay_result_id join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id  join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id join swimmers s on s.id = mrs.swimmer_id where ms.meeting_id = 16101 and  s.complete_name = 'FRANCESCHINI STEFANO' and et.code = 'S4X50MI') a);
