-- /var/www/goggles.org/releases/20180501194821/public/output/201805141647dev_update_passages_sanmarino_2.diff.sql
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";
/*!40101 SET NAMES utf8 */;

--
--
-- PassagesBatchUpdater: recorded from actions by [User: leega (Marco Ligabue) - leegaweb@gmail.com ID: 2]
-- 14 May 2018 16:47:40
-- Begin script
--

INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9061, 0, 47, 54, 143935, 2, 2, '2018-05-14 14:47:40', '2018-05-14 14:47:40', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 47, 54, 0, 760152, NULL, 192, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9062, 0, 53, 2, 143935, 4, 2, '2018-05-14 14:47:40', '2018-05-14 14:47:40', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 40, 56, 0, 760152, NULL, 192, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9063, 0, 53, 72, 143935, 6, 2, '2018-05-14 14:47:41', '2018-05-14 14:47:41', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 34, 28, 0, 760152, NULL, 192, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9064, 0, 53, 98, 143935, 8, 2, '2018-05-14 14:47:41', '2018-05-14 14:47:41', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 28, 26, 0, 760152, NULL, 192, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9065, 0, 38, 85, 143942, 2, 2, '2018-05-14 14:47:41', '2018-05-14 14:47:41', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 38, 85, 0, 760169, NULL, 142, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9066, 0, 46, 55, 143942, 4, 2, '2018-05-14 14:47:41', '2018-05-14 14:47:41', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 25, 40, 0, 760169, NULL, 142, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9067, 0, 46, 60, 143942, 6, 2, '2018-05-14 14:47:41', '2018-05-14 14:47:41', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 12, 0, 0, 760169, NULL, 142, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9068, 0, 46, 30, 143942, 8, 2, '2018-05-14 14:47:41', '2018-05-14 14:47:41', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 58, 30, 0, 760169, NULL, 142, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9069, 0, 34, 16, 143924, 2, 2, '2018-05-14 14:47:41', '2018-05-14 14:47:41', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 34, 16, 0, 760123, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9070, 0, 47, 68, 143924, 4, 2, '2018-05-14 14:47:41', '2018-05-14 14:47:41', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 21, 84, 0, 760123, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9071, 0, 45, 79, 143924, 6, 2, '2018-05-14 14:47:42', '2018-05-14 14:47:42', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 7, 63, 0, 760123, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9072, 0, 39, 78, 143924, 8, 2, '2018-05-14 14:47:42', '2018-05-14 14:47:42', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 47, 41, 0, 760123, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9073, 0, 41, 47, 143951, 2, 2, '2018-05-14 14:47:42', '2018-05-14 14:47:42', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 41, 47, 0, 760208, NULL, 98, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9074, 0, 44, 41, 143951, 4, 2, '2018-05-14 14:47:42', '2018-05-14 14:47:42', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 25, 88, 0, 760208, NULL, 98, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9075, 0, 46, 83, 143951, 6, 2, '2018-05-14 14:47:42', '2018-05-14 14:47:42', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 12, 71, 0, 760208, NULL, 98, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9076, 0, 46, 5, 143951, 8, 2, '2018-05-14 14:47:42', '2018-05-14 14:47:42', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 58, 76, 0, 760208, NULL, 98, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9077, 0, 34, 12, 143960, 2, 2, '2018-05-14 14:47:42', '2018-05-14 14:47:42', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 34, 12, 0, 760291, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9078, 0, 37, 2, 143960, 4, 2, '2018-05-14 14:47:42', '2018-05-14 14:47:42', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 11, 14, 0, 760291, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9079, 0, 39, 56, 143960, 6, 2, '2018-05-14 14:47:42', '2018-05-14 14:47:42', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 50, 70, 0, 760291, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (9080, 0, 40, 53, 143960, 8, 2, '2018-05-14 14:47:42', '2018-05-14 14:47:42', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 31, 23, 0, 760291, NULL, 23, 1);

--
COMMIT;
