-- Leega
-- 17/10/2018
-- Reggioana nuoto setup for CSI 2018/2019 season

--
-- Stagione CSI 2018-2019. Aggiunta dati per la tabella team_affiliations
-- 
INSERT INTO team_affiliations (id,season_id,team_id,name,number,must_calculate_goggle_cup,user_id,lock_version,created_at,updated_at) VALUES 
(5106,181,224,'Reggiana Nuoto','',0,2,0,CURDATE(),CURDATE());

--
-- Stagione CSI 2018-2019. Aggiunta dati dei dati per la tabella swimmers
-- 
INSERT INTO swimmers (id,complete_name,year_of_birth,last_name,first_name,user_id,gender_type_id,lock_version,created_at,updated_at) VALUES 
(38455,'SPAGGIARI LAURA',1990,'SPAGGIARI','LAURA',2,(select t.id from gender_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(38456,'COSTI GIULIA',1992,'COSTI','GIULIA',2,(select t.id from gender_types t where t.code = 'F'),0,CURDATE(),CURDATE());

--
-- Dump dei dati per la tabella badges - 181 - 224
-- 
-- delete from badges where id between 110650 and 110696;
INSERT INTO badges (id,season_id,team_id,swimmer_id,number,user_id,category_type_id,entry_time_type_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(110650,181,224,(select s.id from swimmers s where s.complete_name = 'ANDREOLI RICCARDO' and s.year_of_birth = 1997),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110651,181,224,(select s.id from swimmers s where s.complete_name = 'BALDI DANIELE' and s.year_of_birth = 1982),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110652,181,224,(select s.id from swimmers s where s.complete_name = 'BEDOGNI DAVIDE' and s.year_of_birth = 1974),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110653,181,224,(select s.id from swimmers s where s.complete_name = 'BERTUCCI LUCA' and s.year_of_birth = 1997),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110654,181,224,(select s.id from swimmers s where s.complete_name = 'BONACINI FRANCESCA' and s.year_of_birth = 1962),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M55' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110655,181,224,(select s.id from swimmers s where s.complete_name = 'BORRACCI SARA' and s.year_of_birth = 1988),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110656,181,224,(select s.id from swimmers s where s.complete_name = 'CIGARINI BENEDETTO' and s.year_of_birth = 1993),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110657,181,224,(select s.id from swimmers s where s.complete_name = 'CRISTOFORI ROBERTO' and s.year_of_birth = 1983),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110658,181,224,(select s.id from swimmers s where s.complete_name = 'D''AMBROSIO MARCO ALESSANDRO' and s.year_of_birth = 1966),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110659,181,224,(select s.id from swimmers s where s.complete_name = 'DAOLIO CECILIA' and s.year_of_birth = 1991),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110660,181,224,(select s.id from swimmers s where s.complete_name = 'DAOLIO JESSICA' and s.year_of_birth = 1987),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110661,181,224,(select s.id from swimmers s where s.complete_name = 'DELMONTE ALBERTO' and s.year_of_birth = 1992),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110662,181,224,(select s.id from swimmers s where s.complete_name = 'DI SABATINO FRANCESCA' and s.year_of_birth = 1988),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110663,181,224,(select s.id from swimmers s where s.complete_name = 'DI STASI WILLIAM MARIO' and s.year_of_birth = 1987),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110664,181,224,(select s.id from swimmers s where s.complete_name = 'FERRARI MAURO' and s.year_of_birth = 1968),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110665,181,224,(select s.id from swimmers s where s.complete_name = 'FICARELLI LIA' and s.year_of_birth = 1977),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110666,181,224,(select s.id from swimmers s where s.complete_name = 'FORNACIARI GIULIA' and s.year_of_birth = 1993),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110667,181,224,(select s.id from swimmers s where s.complete_name = 'FRANCHI ALESSANDRO' and s.year_of_birth = 1992),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110668,181,224,(select s.id from swimmers s where s.complete_name = 'GIORGI ROSSI PAOLO' and s.year_of_birth = 1971),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110669,181,224,(select s.id from swimmers s where s.complete_name = 'GIROLIMETTI GRETA' and s.year_of_birth = 1987),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110670,181,224,(select s.id from swimmers s where s.complete_name = 'GIUNCHETI SARA' and s.year_of_birth = 1996),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110671,181,224,(select s.id from swimmers s where s.complete_name = 'GUASTI LUCA' and s.year_of_birth = 1993),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110672,181,224,(select s.id from swimmers s where s.complete_name = 'LASAGNI MARCO' and s.year_of_birth = 1983),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110673,181,224,(select s.id from swimmers s where s.complete_name = 'MARMIROLI MARIA' and s.year_of_birth = 1983),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110674,181,224,(select s.id from swimmers s where s.complete_name = 'MARMIROLI SILVIA' and s.year_of_birth = 1968),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110675,181,224,(select s.id from swimmers s where s.complete_name = 'MAZZIERI ALBERTO' and s.year_of_birth = 1988),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110676,181,224,(select s.id from swimmers s where s.complete_name = 'MENOZZI ANDREA' and s.year_of_birth = 1968),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110677,181,224,(select s.id from swimmers s where s.complete_name = 'ORLANDINI DINO' and s.year_of_birth = 1969),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110678,181,224,(select s.id from swimmers s where s.complete_name = 'PANCIROLI ERIK' and s.year_of_birth = 1973),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110679,181,224,(select s.id from swimmers s where s.complete_name = 'PAOLI MARIA FRANCESCA' and s.year_of_birth = 1986),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110680,181,224,(select s.id from swimmers s where s.complete_name = 'PARISOLI ALESSANDRA' and s.year_of_birth = 1965),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110681,181,224,(select s.id from swimmers s where s.complete_name = 'PATERLINI MATTEO' and s.year_of_birth = 1976),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110682,181,224,(select s.id from swimmers s where s.complete_name = 'QUADRI ANDREA' and s.year_of_birth = 1981),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110683,181,224,(select s.id from swimmers s where s.complete_name = 'RIZZI FABIO' and s.year_of_birth = 1964),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M55' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110684,181,224,(select s.id from swimmers s where s.complete_name = 'SASSI RICCARDO' and s.year_of_birth = 1990),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110685,181,224,(select s.id from swimmers s where s.complete_name = 'SCARANO PIERA' and s.year_of_birth = 1987),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110686,181,224,(select s.id from swimmers s where s.complete_name = 'SCOTTO SALVATORE' and s.year_of_birth = 1985),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110687,181,224,(select s.id from swimmers s where s.complete_name = 'SHAABAN ERIK' and s.year_of_birth = 1988),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110688,181,224,(select s.id from swimmers s where s.complete_name = 'SILVESTRI RAFFAELE' and s.year_of_birth = 1968),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110689,181,224,(select s.id from swimmers s where s.complete_name = 'VACCARI LUCA' and s.year_of_birth = 1993),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110690,181,224,(select s.id from swimmers s where s.complete_name = 'ZANELLA LUCA' and s.year_of_birth = 1998),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110691,181,224,(select s.id from swimmers s where s.complete_name = 'ZINI MARIA GIULIA' and s.year_of_birth = 1992),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110692,181,224,(select s.id from swimmers s where s.complete_name = 'LECCESE LORENZO' and s.year_of_birth = 1993),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110693,181,224,(select s.id from swimmers s where s.complete_name = 'REVERBERI ANDREA' and s.year_of_birth = 1986),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110694,181,224,(select s.id from swimmers s where s.complete_name = 'TORELLI ALBERTO' and s.year_of_birth = 1976),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110695,181,224,(select s.id from swimmers s where s.complete_name = 'COSTI GIULIA' and s.year_of_birth = 1992),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110696,181,224,(select s.id from swimmers s where s.complete_name = 'SPAGGIARI LAURA' and s.year_of_birth = 1990),'?',(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 224 and ta.season_id = 181),0,CURDATE(),CURDATE());

--
-- Stagione CSI 2018-2019. Aggiunta dati per la tabella team_managers
-- 
INSERT INTO team_managers (id,team_affiliation_id,user_id,lock_version,created_at,updated_at) VALUES 
(144,5106,417,0,CURDATE(),CURDATE());

