-- Leega
-- 10/11/2018
-- Setup 181 - 826 (Eden)
--
-- Stagione CSI 2017-2018. Aggiunta dati per la tabella team_affiliations
-- 
INSERT INTO team_affiliations (id,season_id,team_id,name,number,must_calculate_goggle_cup,user_id,lock_version,created_at,updated_at) VALUES 
(5196,181,826,'Eden Sport','',0,2,0,CURDATE(),CURDATE());

--
-- Stagione CSI 2017-2018. Aggiunta dati dei dati per la tabella swimmers
-- 
INSERT INTO swimmers (id,complete_name,year_of_birth,last_name,first_name,user_id,gender_type_id,lock_version,created_at,updated_at) VALUES 
(38498,'MARTELLI SIMONE',1999,'MARTELLI','SIMONE',2,(select t.id from gender_types t where t.code = 'M'),0,CURDATE(),CURDATE());

--
-- Dump dei dati per la tabella badges - 181 - 826
-- 
INSERT INTO badges (id,season_id,team_id,swimmer_id,number,user_id,category_type_id,entry_time_type_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(111350,181,826,(select s.id from swimmers s where s.complete_name = 'ACERBI SARA' and s.year_of_birth = 1996),'AT-04230209',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111351,181,826,(select s.id from swimmers s where s.complete_name = 'ARNESANO RICCARDO' and s.year_of_birth = 1986),'AT-04230210',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111352,181,826,(select s.id from swimmers s where s.complete_name = 'ASPIDOVA LARISSA' and s.year_of_birth = 1965),'AT-04230211',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111353,181,826,(select s.id from swimmers s where s.complete_name = 'BAGNACANI ALESSANDRA' and s.year_of_birth = 1991),'AT-04230212',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111354,181,826,(select s.id from swimmers s where s.complete_name = 'BONFIGLIOLI ANDREA' and s.year_of_birth = 1959),'AT-04230213',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'OVER' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111355,181,826,(select s.id from swimmers s where s.complete_name = 'BONORETTI WILLIAM' and s.year_of_birth = 1962),'AT-04230253',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M55' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111356,181,826,(select s.id from swimmers s where s.complete_name = 'CAMPANA SALVATORE' and s.year_of_birth = 1992),'AT-04230214',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111357,181,826,(select s.id from swimmers s where s.complete_name = 'CAVAZZONI DAVIDE' and s.year_of_birth = 1981),'AT-04230215',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111358,181,826,(select s.id from swimmers s where s.complete_name = 'CODELUPPI FRANCO' and s.year_of_birth = 1963),'AT-04230257',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M55' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111359,181,826,(select s.id from swimmers s where s.complete_name = 'DURMISHI KLITON' and s.year_of_birth = 1978),'AT-04230216',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111360,181,826,(select s.id from swimmers s where s.complete_name = 'ESPOSITO GIUSEPPE' and s.year_of_birth = 1978),'AT-04230217',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111361,181,826,(select s.id from swimmers s where s.complete_name = 'FOSSILE ROBERTO' and s.year_of_birth = 1977),'AT-04230218',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111362,181,826,(select s.id from swimmers s where s.complete_name = 'FRANCHI GUIDO' and s.year_of_birth = 1977),'AT-04230219',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111363,181,826,(select s.id from swimmers s where s.complete_name = 'GUASTALLA FEDERICA' and s.year_of_birth = 1989),'AT-04230220',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111364,181,826,(select s.id from swimmers s where s.complete_name = 'INCERTI ALESSANDRO' and s.year_of_birth = 1982),'AT-04230254',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111365,181,826,(select s.id from swimmers s where s.complete_name = 'INCERTI DELMONTE CHIARA' and s.year_of_birth = 2000),'AT-04230221',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'SEN' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111366,181,826,(select s.id from swimmers s where s.complete_name = 'INCERTI DELMONTE ELISA' and s.year_of_birth = 1996),'AT-04230222',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111367,181,826,(select s.id from swimmers s where s.complete_name = 'INCERTI PAOLO' and s.year_of_birth = 1966),'AT-04230258',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111368,181,826,(select s.id from swimmers s where s.complete_name = 'KAROBBI DYACHYNSKA IRINA' and s.year_of_birth = 1973),'AT-04230223',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111369,181,826,(select s.id from swimmers s where s.complete_name = 'MARTELLI SIMONE' and s.year_of_birth = 1999),'AT-04230224',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111370,181,826,(select s.id from swimmers s where s.complete_name = 'MIARI FRANCESCO' and s.year_of_birth = 1991),'AT-04230225',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111371,181,826,(select s.id from swimmers s where s.complete_name = 'MONTANARI FRANCESCO' and s.year_of_birth = 1980),'AT-04230226',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111372,181,826,(select s.id from swimmers s where s.complete_name = 'MONTANARI MARTINA' and s.year_of_birth = 1996),'AT-04230227',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111373,181,826,(select s.id from swimmers s where s.complete_name = 'MONTI MARCO' and s.year_of_birth = 1986),'AT-04230228',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111374,181,826,(select s.id from swimmers s where s.complete_name = 'ORLANDINI EDO' and s.year_of_birth = 1961),'AT-04230229',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M55' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111375,181,826,(select s.id from swimmers s where s.complete_name = 'PAPA ANTONIO' and s.year_of_birth = 1984),'AT-04230230',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111376,181,826,(select s.id from swimmers s where s.complete_name = 'PASQUALI CHIARA' and s.year_of_birth = 1980),'AT-04230231',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111377,181,826,(select s.id from swimmers s where s.complete_name = 'REGNANI FEDERICO' and s.year_of_birth = 1988),'AT-04230232',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111378,181,826,(select s.id from swimmers s where s.complete_name = 'ROTA CAMILLA' and s.year_of_birth = 1989),'AT-04230255',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111379,181,826,(select s.id from swimmers s where s.complete_name = 'RUSEANOVSCHI OLGA' and s.year_of_birth = 1983),'AT-04230256',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111380,181,826,(select s.id from swimmers s where s.complete_name = 'SIRINGO ALESSIA' and s.year_of_birth = 1982),'AT-04230233',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111381,181,826,(select s.id from swimmers s where s.complete_name = 'ZACCARELLI MARCO' and s.year_of_birth = 1965),'AT-04230234',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(111382,181,826,(select s.id from swimmers s where s.complete_name = 'ZAGATTI ALESSANDRO' and s.year_of_birth = 1974),'AT-04230235',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 826 and ta.season_id = 181),0,CURDATE(),CURDATE());

--
-- Stagione CSI 2018-2019. Aggiunta dati per la tabella team_managers
-- 
INSERT INTO team_managers (id,team_affiliation_id,user_id,lock_version,created_at,updated_at) VALUES 
(147,5196,176,0,CURDATE(),CURDATE());

/*
select s.complete_name, s.year_of_birth, b.number, ct.code
from badges b
	join swimmers s on s.id = b.swimmer_id
	join category_types ct on ct.id = b.category_type_id
where b.team_affiliation_id = 5196;
/*