-- Leega
-- 18/10/2018
-- Team 1 setup for season 181
--
-- Stagione CSI 2016-2017. Aggiunta dati per la tabella team_affiliations
-- 
INSERT INTO team_affiliations (id,season_id,team_id,name,number,must_calculate_goggle_cup,user_id,lock_version,created_at,updated_at) VALUES 
(5107,181,1,'CSInuoto OberFerrari','04200002',1,2,0,CURDATE(),CURDATE());

--
-- Stagione CSI 2016-2017. Aggiunta dati dei dati per la tabella swimmers
-- 
INSERT INTO swimmers (id,complete_name,year_of_birth,last_name,first_name,user_id,gender_type_id,lock_version,created_at,updated_at) VALUES 
(38457,'BARBIERI LUCA',1989,'BARBIERI','LUCA',2,(select t.id from gender_types t where t.code = 'M'),0,CURDATE(),CURDATE()),
(38458,'DAZZI CLAUDIA',1981,'DAZZI','CLAUDIA',2,(select t.id from gender_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(38459,'RE STEFANIA',1977,'RE','STEFANIA',2,(select t.id from gender_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(38460,'CROCCO STEFANO',1970,'CROCCO','STEFANO',2,(select t.id from gender_types t where t.code = 'M'),0,CURDATE(),CURDATE());

--
-- Dump dei dati per la tabella badges - 181 - 1
-- 
-- delete from badges where id between 110697 and 110751;
INSERT INTO badges (id,season_id,team_id,swimmer_id,number,user_id,category_type_id,entry_time_type_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(110697,181,1,(select s.id from swimmers s where s.complete_name = 'ALLORO STEFANO' and s.year_of_birth = 1969),'AT04207999',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110698,181,1,(select s.id from swimmers s where s.complete_name = 'AMMIRATI GIUSY' and s.year_of_birth = 2003),'ATA4208001',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'SEN' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110699,181,1,(select s.id from swimmers s where s.complete_name = 'ARMANI VERONICA' and s.year_of_birth = 2000),'AT04208015',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'SEN' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110700,181,1,(select s.id from swimmers s where s.complete_name = 'ATTOLINI FEDERICO' and s.year_of_birth = 1962),'AT04208017',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M55' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110701,181,1,(select s.id from swimmers s where s.complete_name = 'BARBIERI LUCA' and s.year_of_birth = 1989),'AT04208036',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110702,181,1,(select s.id from swimmers s where s.complete_name = 'BIANCHI ELENA' and s.year_of_birth = 1967),'AT04214510',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110703,181,1,(select s.id from swimmers s where s.complete_name = 'BONACINI MONICA' and s.year_of_birth = 1969),'AT04214512',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110704,181,1,(select s.id from swimmers s where s.complete_name = 'BONI CLAUDIO' and s.year_of_birth = 1994),'AT04208109',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110705,181,1,(select s.id from swimmers s where s.complete_name = 'BONOMI ALESSIO' and s.year_of_birth = 1988),'AT04208119',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110706,181,1,(select s.id from swimmers s where s.complete_name = 'BRAGLIA LUCA' and s.year_of_birth = 1979),'AT04208136',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110707,181,1,(select s.id from swimmers s where s.complete_name = 'BURANI PIETRO' and s.year_of_birth = 1991),'AT04208151',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110708,181,1,(select s.id from swimmers s where s.complete_name = 'CARLETTI ALAN' and s.year_of_birth = 1997),'AT04208187',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110709,181,1,(select s.id from swimmers s where s.complete_name = 'DAZZI CLAUDIA' and s.year_of_birth = 1981),'AT04208282',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110710,181,1,(select s.id from swimmers s where s.complete_name = 'DELMONTE ILARIA ' and s.year_of_birth = 1991),'AT04208293',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110711,181,1,(select s.id from swimmers s where s.complete_name = 'DENTI ANDREA' and s.year_of_birth = 1969),'AT04208296',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110712,181,1,(select s.id from swimmers s where s.complete_name = 'FANTUZZI LUCA' and s.year_of_birth = 1971),'AT04208324',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110713,181,1,(select s.id from swimmers s where s.complete_name = 'FERRARI ALESSIA' and s.year_of_birth = 1978),'AT04208331',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110714,181,1,(select s.id from swimmers s where s.complete_name = 'FERRARI FABIO' and s.year_of_birth = 1981),'AT04209610',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110715,181,1,(select s.id from swimmers s where s.complete_name = 'FERRARI FRANCESCO' and s.year_of_birth = 1988),'AT04209611',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110716,181,1,(select s.id from swimmers s where s.complete_name = 'FERRARI SIMONE' and s.year_of_birth = 1996),'AT04208339',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110717,181,1,(select s.id from swimmers s where s.complete_name = 'FORMENTINI DAVIDE' and s.year_of_birth = 1988),'AT04208377',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110718,181,1,(select s.id from swimmers s where s.complete_name = 'FRANCESCHINI STEFANO' and s.year_of_birth = 1973),'AT04202386',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110719,181,1,(select s.id from swimmers s where s.complete_name = 'GANGAROSSA DAVIDE' and s.year_of_birth = 1966),'AT04208400',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110720,181,1,(select s.id from swimmers s where s.complete_name = 'IORI PIETRO' and s.year_of_birth = 2002),'AT04208505',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'SEN' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110721,181,1,(select s.id from swimmers s where s.complete_name = 'KOCI KLERI' and s.year_of_birth = 2003),'AT04210462',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'SEN' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110722,181,1,(select s.id from swimmers s where s.complete_name = 'LEONARDI ELISA' and s.year_of_birth = 1975),'AT04208529',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110723,181,1,(select s.id from swimmers s where s.complete_name = 'LEONCINI VALERIA' and s.year_of_birth = 1976),'AT04208533',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110724,181,1,(select s.id from swimmers s where s.complete_name = 'LIGABUE MARCO' and s.year_of_birth = 1971),'AT04216543',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110725,181,1,(select s.id from swimmers s where s.complete_name = 'ORLANDINI IDO PIERALDO' and s.year_of_birth = 1957),'AT04208699',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'OVER' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110726,181,1,(select s.id from swimmers s where s.complete_name = 'PANZETTI NAILA' and s.year_of_birth = 1990),'AT04208720',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110727,181,1,(select s.id from swimmers s where s.complete_name = 'PASCALE CIRO' and s.year_of_birth = 2003),'AT04208728',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'SEN' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110728,181,1,(select s.id from swimmers s where s.complete_name = 'PESARE REBECCA' and s.year_of_birth = 1995),'AT04208756',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110729,181,1,(select s.id from swimmers s where s.complete_name = 'PEZZI STEFANIA' and s.year_of_birth = 1981),'AT04208757',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110730,181,1,(select s.id from swimmers s where s.complete_name = 'PEZZOLI GIANLUCA' and s.year_of_birth = 1992),'AT04208758',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110731,181,1,(select s.id from swimmers s where s.complete_name = 'RE STEFANIA ' and s.year_of_birth = 1977),'AT04209612 ',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110732,181,1,(select s.id from swimmers s where s.complete_name = 'RINALDINI ROBERTO' and s.year_of_birth = 1986),'AT04208820',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110733,181,1,(select s.id from swimmers s where s.complete_name = 'RONZONI ALESSANDRO' and s.year_of_birth = 1984),'AT04208824',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110734,181,1,(select s.id from swimmers s where s.complete_name = 'SADDI FRANCISCO JAVIER' and s.year_of_birth = 1989),'AT04220328',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110735,181,1,(select s.id from swimmers s where s.complete_name = 'SCALA MATTIA' and s.year_of_birth = 1990),'AT04208865',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110736,181,1,(select s.id from swimmers s where s.complete_name = 'SESENA BARBARA' and s.year_of_birth = 1971),'AT04208880',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110737,181,1,(select s.id from swimmers s where s.complete_name = 'SESENA PATRIZIA' and s.year_of_birth = 1974),'AT04208881',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110738,181,1,(select s.id from swimmers s where s.complete_name = 'STORCHI LORENZO' and s.year_of_birth = 1999),'AT04208904',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110739,181,1,(select s.id from swimmers s where s.complete_name = 'TOFFANETTI LAURA' and s.year_of_birth = 1973),'AT04208928',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110740,181,1,(select s.id from swimmers s where s.complete_name = 'VEZZANI GIORGIA' and s.year_of_birth = 1995),'AT04208966',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110741,181,1,(select s.id from swimmers s where s.complete_name = 'BRUNI SIMONE' and s.year_of_birth = 1978),'AT04224551',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110742,181,1,(select s.id from swimmers s where s.complete_name = 'BENASSI SARA' and s.year_of_birth = 1985),'AT04224552',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110743,181,1,(select s.id from swimmers s where s.complete_name = 'BERTOCCHI FABIO' and s.year_of_birth = 1996),'AT04224553',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110744,181,1,(select s.id from swimmers s where s.complete_name = 'CANTONI SAMANTA' and s.year_of_birth = 1988),'AT04224554',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110745,181,1,(select s.id from swimmers s where s.complete_name = 'DEL RIO SIMONE' and s.year_of_birth = 1983),'AT04224555',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110746,181,1,(select s.id from swimmers s where s.complete_name = 'GIANSOLDATI MATTEO' and s.year_of_birth = 1989),'AT04224556',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110747,181,1,(select s.id from swimmers s where s.complete_name = 'NOVELLI MICHELE' and s.year_of_birth = 1975),'AT04224557',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110748,181,1,(select s.id from swimmers s where s.complete_name = 'AMATO ROSSANA' and s.year_of_birth = 1982),'AT04224558',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110749,181,1,(select s.id from swimmers s where s.complete_name = 'BERTOZZI ORLANDO' and s.year_of_birth = 1968),'AT04224559',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110750,181,1,(select s.id from swimmers s where s.complete_name = 'CROCCO STEFANO' and s.year_of_birth = 1970),'?',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(110751,181,1,(select s.id from swimmers s where s.complete_name = 'BERTANI STEFANO' and s.year_of_birth = 1974),'?',(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE());


--
-- Stagione CSI 2018-2019. Aggiunta dati per la tabella team_managers
-- 
INSERT INTO team_managers (id,team_affiliation_id,user_id,lock_version,created_at,updated_at) VALUES 
(145,5107,2,0,CURDATE(),CURDATE());
