-- Leega
-- 10/11/2018
-- Setup 182 - 1
--
-- Affiliazione CSI per FIN 182 team_affiliations
-- 
INSERT INTO team_affiliations (id,season_id,team_id,name,number,must_calculate_goggle_cup,user_id,lock_version,created_at,updated_at) VALUES 
(5197,182,1,'CSI NUOTO OBER FERRARI','46103',1,2,0,CURDATE(),CURDATE());

--
-- Dump dei dati per la tabella badges
-- 
INSERT INTO badges (id,season_id,team_id,swimmer_id,number,user_id,category_type_id,entry_time_type_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(111386,182,1,(select s.id from swimmers s where s.complete_name = 'ALLORO STEFANO' and s.year_of_birth = 1969),'43446',2,(select t.id from category_types t where t.code = 'M50' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111387,182,1,(select s.id from swimmers s where s.complete_name = 'BENASSI SARA' and s.year_of_birth = 1985),'616493',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111388,182,1,(select s.id from swimmers s where s.complete_name = 'BERTOZZI ORLANDO' and s.year_of_birth = 1968),'431310',2,(select t.id from category_types t where t.code = 'M50' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111389,182,1,(select s.id from swimmers s where s.complete_name = 'BIANCHI ELENA' and s.year_of_birth = 1967),'53593',2,(select t.id from category_types t where t.code = 'M50' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111390,182,1,(select s.id from swimmers s where s.complete_name = 'BONACINI MONICA' and s.year_of_birth = 1969),'50333',2,(select t.id from category_types t where t.code = 'M50' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111391,182,1,(select s.id from swimmers s where s.complete_name = 'BONOMI ALESSIO' and s.year_of_birth = 1988),'45611',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111392,182,1,(select s.id from swimmers s where s.complete_name = 'BRUNI SIMONE' and s.year_of_birth = 1978),'505022',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111393,182,1,(select s.id from swimmers s where s.complete_name = 'CANOVI GABRIELE' and s.year_of_birth = 1980),'754167',2,(select t.id from category_types t where t.code = 'M35' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111394,182,1,(select s.id from swimmers s where s.complete_name = 'CANTONI SAMANTA' and s.year_of_birth = 1988),'754166',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111395,182,1,(select s.id from swimmers s where s.complete_name = 'DEL RIO SIMONE' and s.year_of_birth = 1983),'484098',2,(select t.id from category_types t where t.code = 'M35' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111396,182,1,(select s.id from swimmers s where s.complete_name = 'FERRARI ALESSIA' and s.year_of_birth = 1978),'52696',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111397,182,1,(select s.id from swimmers s where s.complete_name = 'FORMENTINI DAVIDE' and s.year_of_birth = 1988),'107119',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111398,182,1,(select s.id from swimmers s where s.complete_name = 'FRANCESCHINI STEFANO' and s.year_of_birth = 1973),'393637',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111399,182,1,(select s.id from swimmers s where s.complete_name = 'GIANSOLDATI MATTEO' and s.year_of_birth = 1989),'40667',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111400,182,1,(select s.id from swimmers s where s.complete_name = 'LEONARDI ELISA' and s.year_of_birth = 1975),'48891',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111401,182,1,(select s.id from swimmers s where s.complete_name = 'LEONCINI VALERIA' and s.year_of_birth = 1976),'46597',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111402,182,1,(select s.id from swimmers s where s.complete_name = 'LIGABUE MARCO' and s.year_of_birth = 1971),'53594',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111403,182,1,(select s.id from swimmers s where s.complete_name = 'MATTIOLI ALESSANDRO' and s.year_of_birth = 1967),'46483',2,(select t.id from category_types t where t.code = 'M50' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111404,182,1,(select s.id from swimmers s where s.complete_name = 'NOVELLI MICHELE' and s.year_of_birth = 1975),'880873',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111405,182,1,(select s.id from swimmers s where s.complete_name = 'ORLANDINI IDO PIERALDO' and s.year_of_birth = 1957),'52673',2,(select t.id from category_types t where t.code = 'M60' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111406,182,1,(select s.id from swimmers s where s.complete_name = 'PANZETTI NAILA' and s.year_of_birth = 1990),'42981',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111407,182,1,(select s.id from swimmers s where s.complete_name = 'PEZZI STEFANIA' and s.year_of_birth = 1981),'686370',2,(select t.id from category_types t where t.code = 'M35' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111408,182,1,(select s.id from swimmers s where s.complete_name = 'RONZONI ALESSANDRO' and s.year_of_birth = 1984),'497872',2,(select t.id from category_types t where t.code = 'M35' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111409,182,1,(select s.id from swimmers s where s.complete_name = 'SESENA BARBARA' and s.year_of_birth = 1971),'53592',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111410,182,1,(select s.id from swimmers s where s.complete_name = 'TOFFANETTI LAURA' and s.year_of_birth = 1973),'43439',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111411,182,1,(select s.id from swimmers s where s.complete_name = 'TOSI VALENTINA' and s.year_of_birth = 1989),'571103',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111412,182,1,(select s.id from swimmers s where s.complete_name = 'VALCAVI LUCA' and s.year_of_birth = 1988),'385163',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111413,182,1,(select s.id from swimmers s where s.complete_name = 'BERTOCCHI FABIO' and s.year_of_birth = 1996),'609981',2,(select t.id from category_types t where t.code = 'U25' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE()),
(111414,182,1,(select s.id from swimmers s where s.complete_name = 'VEZZANI GIORGIA' and s.year_of_birth = 1995),'817133',2,(select t.id from category_types t where t.code = 'U25' and t.season_id = 182),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 182),0,CURDATE(),CURDATE());

--
-- Stagione CSI 2018-2019. Aggiunta dati per la tabella team_managers
-- 
INSERT INTO team_managers (id,team_affiliation_id,user_id,lock_version,created_at,updated_at) VALUES 
(148,5197,2,0,CURDATE(),CURDATE());

/*
select s.complete_name, s.year_of_birth, b.number, ct.code
from badges b
	join swimmers s on s.id = b.swimmer_id
	join category_types ct on ct.id = b.category_type_id
where b.team_affiliation_id = 5197;
/*