-- Leega
-- 23/11/2019
-- Badge payments

-- select * from badge_payments
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(69,'Saldo ed acconto','2019-11-19','128',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'ROTA CAMILLA' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());

-- Final cash 2108/2019
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(101,'Saldo 2018-2019','2019-11-19','-24.5',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'ALLORO STEFANO' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(102,'Saldo 2018-2019','2019-11-19','-10.5',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BENASSI SARA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(103,'Saldo 2018-2019','2019-11-19','-364.5',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BERTOZZI ORLANDO' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(104,'Saldo 2018-2019','2019-11-19','1',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BIANCHI ELENA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(105,'Saldo 2018-2019','2019-11-19','2',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BONACINI MONICA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(106,'Saldo 2018-2019','2019-11-19','-47.2',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'DEL RIO SIMONE' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(107,'Saldo 2018-2019','2019-11-19','85.5',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'FERRARI ALESSIA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(108,'Saldo 2018-2019','2019-11-19','3',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'FORMENTINI DAVIDE' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(109,'Saldo 2018-2019','2019-11-19','-6',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'FRANCESCHINI STEFANO' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(110,'Saldo 2018-2019','2019-11-19','3.2',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'GIANSOLDATI MATTEO' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(111,'Saldo 2018-2019','2019-11-19','8.5',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'LEONARDI ELISA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(112,'Saldo 2018-2019','2019-11-19','-145',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'LIGABUE MARCO' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(113,'Saldo 2018-2019','2019-11-19','-3.5',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'NOVELLI MICHELE' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(114,'Saldo 2018-2019','2019-11-19','36',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'PANZETTI NAILA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(115,'Saldo 2018-2019','2019-11-19','25.5',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'PEZZI STEFANIA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(116,'Saldo 2018-2019','2019-11-19','-33',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'RONZONI ALESSANDRO' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(117,'Saldo 2018-2019','2019-11-19','12',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'ROTA CAMILLA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(118,'Saldo 2018-2019','2019-11-19','48.5',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'SESENA BARBARA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(119,'Saldo 2018-2019','2019-11-19','-24',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'SIRINGO ALESSIA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(120,'Saldo 2018-2019','2019-11-19','5',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'TOFFANETTI LAURA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(121,'Saldo 2018-2019','2019-11-19','33',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'VALCAVI LUCA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());

-- Season 191-192
-- delete from badge_payments where id >= 130;
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(130,'Tesseramento FIN/CSI 19/20','2019-10-19','34',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'NOVELLI MICHELE' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(131,'Tesseramento FIN/CSI 19/20','2019-10-19','34',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BENASSI SARA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(132,'Tesseramento FIN/CSI 19/20','2019-10-19','34',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'GIANSOLDATI MATTEO' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(133,'Tesseramento FIN/CSI 19/20','2019-10-19','34',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'CANTONI SAMANTA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(134,'Tesseramento FIN/CSI 19/20','2019-10-19','34',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'DEL RIO SIMONE' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(135,'Tesseramento FIN/CSI 19/20','2019-10-19','34',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BERTOCCHI FABIO' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(136,'Tesseramento FIN/CSI 19/20','2019-10-19','34',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'FRIGIERI ALBERTO' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(137,'Tesseramento CSI 19/20','2019-10-19','10',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'AMATO ROSSANA' and b.team_id = 1 and b.season_id = 191),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(138,'Tesseramento FIN 19/20','2019-10-19','24',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'CANOVI GABRIELE' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(139,'Iscrizione gare FIN 2019/2020','2018-10-18','60',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'LEONARDI ELISA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(140,'Tesseramento e prima gara CSI','2019-11-19','18.6',1,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BONI ALESSANDRO' and b.team_id = 1 and b.season_id = 191),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(141,'Tesseramento e prima gara CSI','2019-11-19','18.6',1,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'FEDERICI ZUCCOLINI ANTONIO' and b.team_id = 1 and b.season_id = 191),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(142,'Tesseramento e prima gara CSI','2019-11-19','18.6',1,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'GALASSO MANIELO' and b.team_id = 1 and b.season_id = 191),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(143,'Tesseramento e prima gara CSI','2019-11-19','18.6',1,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'MURANO SALVATORE' and b.team_id = 1 and b.season_id = 191),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(144,'Tesseramento e prima gara CSI','2019-11-19','18.6',1,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'MUSARO GIUSEPPE' and b.team_id = 1 and b.season_id = 191),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(145,'Tesseramento e prima gara CSI','2019-11-19','14.3',1,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'PETROZZELLI ANTONELLA' and b.team_id = 1 and b.season_id = 191),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(146,'Tesseramento FIN e iscrizione gara','2019-11-19','36',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BONI ALESSANDRO' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(147,'Cartellini FIN+CSI 19/20','2019-11-19','34',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BRUNI SIMONE' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(148,'Gara FIN Bologna','2019-11-19','12',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'FORMENTINI DAVIDE' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(149,'Gare FIN Bologna 2019','2019-11-19','14',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BRUNI SIMONE' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES(150,'Quota Gianluca Pezzoli gare Bologna 17/11 e Parma 15/12','2019-11-19','24',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'PEZZOLI GIANLUCA' and b.team_id = 1 and b.season_id = 192),2,0,CURDATE(),CURDATE());