-- Leega
-- 31/10/2019
-- 1_191_setup

INSERT INTO swimmers (id,complete_name,year_of_birth,last_name,first_name,user_id,gender_type_id,lock_version,created_at,updated_at) VALUES 
(40584,'COLLI SABRINA',2000,'COLLI','SABRINA',2,(select t.id from gender_types t where t.code = 'F'),0,CURDATE(),CURDATE());

-- delete from badges where id between 125001 and 125012;
INSERT INTO badges (id,season_id,team_id,swimmer_id,number,is_out_of_goggle_cup,user_id,category_type_id,entry_time_type_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(125001,191,1,(select s.id from swimmers s where s.complete_name = 'CAVAZZONI DAVIDE' and s.year_of_birth = 1981),'04224048',0,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M35' and t.season_id = 191),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 191),0,CURDATE(),CURDATE()),
(125002,191,1,(select s.id from swimmers s where s.complete_name = 'COLLI SABRINA' and s.year_of_birth = 2000),'04224049',0,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'SEN' and t.season_id = 191),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 191),0,CURDATE(),CURDATE()),
(125003,191,1,(select s.id from swimmers s where s.complete_name = 'ESPOSITO GIUSEPPE' and s.year_of_birth = 1978),'04224050',0,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 191),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 191),0,CURDATE(),CURDATE()),
(125004,191,1,(select s.id from swimmers s where s.complete_name = 'FOSSILE ROBERTO' and s.year_of_birth = 1977),'04224051',0,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 191),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 191),0,CURDATE(),CURDATE()),
(125005,191,1,(select s.id from swimmers s where s.complete_name = 'IOTTI FLAVIO' and s.year_of_birth = 1978),'04224052',0,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M40' and t.season_id = 191),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 191),0,CURDATE(),CURDATE()),
(125006,191,1,(select s.id from swimmers s where s.complete_name = 'MIARI FRANCESCO' and s.year_of_birth = 1991),'04224053',0,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 191),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 191),0,CURDATE(),CURDATE()),
(125007,191,1,(select s.id from swimmers s where s.complete_name = 'MONTANARI MARTINA' and s.year_of_birth = 1996),'04224054',0,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 191),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 191),0,CURDATE(),CURDATE()),
(125008,191,1,(select s.id from swimmers s where s.complete_name = 'PIOLI ALICE' and s.year_of_birth = 1986),'04224056',0,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 191),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 191),0,CURDATE(),CURDATE()),
(125009,191,1,(select s.id from swimmers s where s.complete_name = 'TAMAGNINI ANDREA SERGIO' and s.year_of_birth = 1991),'04204347',0,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 191),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 191),0,CURDATE(),CURDATE()),
(125010,191,1,(select s.id from swimmers s where s.complete_name = 'PASCALE CIRO' and s.year_of_birth = 2003),'04204335',1,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'SEN' and t.season_id = 191),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 191),0,CURDATE(),CURDATE()),
(125011,191,1,(select s.id from swimmers s where s.complete_name = 'COSTOLI BARBARA' and s.year_of_birth = 2006),'04220546',1,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'SEN' and t.season_id = 191),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 191),0,CURDATE(),CURDATE()),
(125012,191,1,(select s.id from swimmers s where s.complete_name = 'FRIGIERI ALBERTO' and s.year_of_birth = 1987),'',0,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 191),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 191),0,CURDATE(),CURDATE());

-- select * from badges b where b.swimmer_id is null;