-- Leega
-- 05/08/2019
-- Badge payment updates

-- select * from badge_payments bp order by bp.payment_date;

-- Fix wrong Monika payment date
update badge_payments set payment_date = '2019-02-18' where id = 38;

-- New payments
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (39,'Pagamenti gare fin arretrati','2019-02-25','100',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BUDASSI VALENTINA' and b.team_id = 1 and b.season_id = 172),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (40,'Gara Bologna FIN 2019','2019-02-28','14',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BRUNI SIMONE' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (41,'Gara Fin Sassuolo','2019-04-08','15',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'FORMENTINI DAVIDE' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (42,'Gare FIN Baby','2019-04-09','50',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'SESENA BARBARA' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (43,'Sassuolo FIN aprile 2019','2019-04-09','15',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BRUNI SIMONE' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (44,'Gara Bologna e Sassuolo FIN','2019-04-18','24',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'ACERBI SARA' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (45,'Staffette FIN Sassuolo','2019-04-08','3.5',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'FORMENTINI DAVIDE' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (46,'Gare San Marino FIN maggio 2019','2019-05-16','15',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BRUNI SIMONE' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (47,'Pagamento gare 2018/2019','2019-05-29','150',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'DEL RIO SIMONE' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (48,'Pagamento gare fin 2018/2019','2019-06-07','34',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'VEZZANI GIORGIA' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (49,'Campionati estivi FIN Riccione','2019-06-10','21',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'FORMENTINI DAVIDE' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (50,'Saldo iscrizioni gare stagione 18-19','2019-06-10','55',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'PANZETTI NAILA' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (51,'Gare','2019-06-11','100',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BIANCHI ELENA' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (52,'Gare FIN Baby','2019-06-19','50',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'SESENA BARBARA' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());
insert into badge_payments (id,notes,payment_date,amount,is_manual,badge_id,user_id,lock_version,created_at,updated_at) VALUES (53,'Simone Bruni italiani. Riccione','2019-07-03','15',0,(select b.id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BRUNI SIMONE' and b.team_id = 1 and b.season_id = 182),2,0,CURDATE(),CURDATE());


