-- Leega
-- 28/02/2019
-- Add Ober Ferrari swimmers and badges for Reggio

INSERT INTO swimmers (id,complete_name,year_of_birth,last_name,first_name,user_id,gender_type_id,lock_version,created_at,updated_at) VALUES 
(40127,'COSTOLI BARBARA',2006,'COSTOLI','BARBARA',2,(select t.id from gender_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(40128,'PARRILLO ANNA CHIARA',1996,'PARRILLO','ANNA CHIARA',2,(select t.id from gender_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(40129,'ESPOSITO FEDERICA',2006,'ESPOSITO','FEDERICA',2,(select t.id from gender_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(40130,'FAINA DAVID',1998,'FAINA','DAVID',2,(select t.id from gender_types t where t.code = 'M'),0,CURDATE(),CURDATE()),
(40131,'FANTINI FILIPPO',2002,'FANTINI','FILIPPO',2,(select t.id from gender_types t where t.code = 'M'),0,CURDATE(),CURDATE());

INSERT INTO badges (id,season_id,team_id,swimmer_id,number,is_out_of_goggle_cup,user_id,category_type_id,entry_time_type_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(123230,181,1,(select s.id from swimmers s where s.complete_name = 'SPAGGIARI ELENA' and s.year_of_birth = 1970),'04208898',0,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(123231,181,1,(select s.id from swimmers s where s.complete_name = 'FOSCATO FAUSTO' and s.year_of_birth = 1965),'04208383',0,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M50' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(123232,181,1,(select s.id from swimmers s where s.complete_name = 'TAMAGNINI ANDREA SERGIO' and s.year_of_birth = 1991),'04242296',0,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(123233,181,1,(select s.id from swimmers s where s.complete_name = 'PESENTI GABRIELE' and s.year_of_birth = 1998),'04242295',0,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(123234,181,1,(select s.id from swimmers s where s.complete_name = 'FAINA DAVID' and s.year_of_birth = 1998),'04242292',0,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(123235,181,1,(select s.id from swimmers s where s.complete_name = 'FANTINI FILIPPO' and s.year_of_birth = 2002),'04242293',1,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'SEN' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(123236,181,1,(select s.id from swimmers s where s.complete_name = 'PARRILLO ANNA CHIARA' and s.year_of_birth = 1996),'04242294',0,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M20' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(123237,181,1,(select s.id from swimmers s where s.complete_name = 'COSTOLI BARBARA' and s.year_of_birth = 2006),'04208264',1,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'SEN' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE()),
(123238,181,1,(select s.id from swimmers s where s.complete_name = 'ESPOSITO FEDERICA' and s.year_of_birth = 2006),'04214521',1,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'SEN' and t.season_id = 181),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 181),0,CURDATE(),CURDATE());
