-- Leega
-- 14/10/2019

--
 -- Affiliazione CSI per FIN 192 team_affiliations
 -- 
INSERT INTO team_affiliations (id,season_id,team_id,name,number,must_calculate_goggle_cup,user_id,lock_version,created_at,updated_at) VALUES 
(5726,192,1,'CSI NUOTO OBER FERRARI','46103',1,2,0,CURDATE(),CURDATE());

--
 -- Stagione FIN 2019-2020. Aggiunta dati dei dati per la tabella swimmers
 -- 
INSERT INTO swimmers (id,complete_name,year_of_birth,last_name,first_name,user_id,gender_type_id,lock_version,created_at,updated_at) VALUES 
(40583,'FRIGIERI ALBERTO',1983,'FRIGIERI','ALBERTO',2,(select t.id from gender_types t where t.code = 'M'),0,CURDATE(),CURDATE());

--
 -- Dump dei dati per la tabella badges
 -- 
INSERT INTO badges (id,season_id,team_id,swimmer_id,number,user_id,category_type_id,entry_time_type_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(124914,192,1,(select s.id from swimmers s where s.complete_name = 'ALLORO STEFANO' and s.year_of_birth = 1969),'43446',2,(select t.id from category_types t where t.code = 'M50' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124915,192,1,(select s.id from swimmers s where s.complete_name = 'BENASSI SARA' and s.year_of_birth = 1985),'616493',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124916,192,1,(select s.id from swimmers s where s.complete_name = 'BERTOCCHI FABIO' and s.year_of_birth = 1996),'609981',2,(select t.id from category_types t where t.code = 'U25' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124917,192,1,(select s.id from swimmers s where s.complete_name = 'BIANCHI ELENA' and s.year_of_birth = 1967),'53593',2,(select t.id from category_types t where t.code = 'M50' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124918,192,1,(select s.id from swimmers s where s.complete_name = 'BONACINI MONICA' and s.year_of_birth = 1969),'50333',2,(select t.id from category_types t where t.code = 'M50' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124919,192,1,(select s.id from swimmers s where s.complete_name = 'BONI ALESSANDRO' and s.year_of_birth = 1988),'',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124920,192,1,(select s.id from swimmers s where s.complete_name = 'BONOMI ALESSIO' and s.year_of_birth = 1988),'45611',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124921,192,1,(select s.id from swimmers s where s.complete_name = 'BRUNI SIMONE' and s.year_of_birth = 1978),'505022',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124922,192,1,(select s.id from swimmers s where s.complete_name = 'CANOVI GABRIELE' and s.year_of_birth = 1980),'754167',2,(select t.id from category_types t where t.code = 'M35' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124923,192,1,(select s.id from swimmers s where s.complete_name = 'CANTONI SAMANTA' and s.year_of_birth = 1988),'754166',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124924,192,1,(select s.id from swimmers s where s.complete_name = 'CARLETTI ALAN' and s.year_of_birth = 1997),'',2,(select t.id from category_types t where t.code = 'U25' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124925,192,1,(select s.id from swimmers s where s.complete_name = 'DEL RIO SIMONE' and s.year_of_birth = 1983),'484098',2,(select t.id from category_types t where t.code = 'M35' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124926,192,1,(select s.id from swimmers s where s.complete_name = 'FERRARI ALESSIA' and s.year_of_birth = 1978),'52696',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124927,192,1,(select s.id from swimmers s where s.complete_name = 'FORMENTINI DAVIDE' and s.year_of_birth = 1988),'107119',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124928,192,1,(select s.id from swimmers s where s.complete_name = 'FRANCESCHINI STEFANO' and s.year_of_birth = 1973),'393637',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124929,192,1,(select s.id from swimmers s where s.complete_name = 'FRIGIERI ALBERTO' and s.year_of_birth = 1983),'',2,(select t.id from category_types t where t.code = 'M35' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124930,192,1,(select s.id from swimmers s where s.complete_name = 'GIANSOLDATI MATTEO' and s.year_of_birth = 1989),'40667',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124931,192,1,(select s.id from swimmers s where s.complete_name = 'LEONARDI ELISA' and s.year_of_birth = 1975),'48891',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124932,192,1,(select s.id from swimmers s where s.complete_name = 'LEONCINI VALERIA' and s.year_of_birth = 1976),'46597',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124933,192,1,(select s.id from swimmers s where s.complete_name = 'LIGABUE MARCO' and s.year_of_birth = 1971),'53594',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124934,192,1,(select s.id from swimmers s where s.complete_name = 'MARTIGNANI ALBERTO' and s.year_of_birth = 1961),'',2,(select t.id from category_types t where t.code = 'M55' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124935,192,1,(select s.id from swimmers s where s.complete_name = 'NOVELLI MICHELE' and s.year_of_birth = 1975),'880873',2,(select t.id from category_types t where t.code = 'M40' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124936,192,1,(select s.id from swimmers s where s.complete_name = 'ORLANDINI IDO PIERALDO' and s.year_of_birth = 1957),'52673',2,(select t.id from category_types t where t.code = 'M60' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124937,192,1,(select s.id from swimmers s where s.complete_name = 'PANZETTI NAILA' and s.year_of_birth = 1990),'42981',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124938,192,1,(select s.id from swimmers s where s.complete_name = 'PEZZI STEFANIA' and s.year_of_birth = 1981),'686370',2,(select t.id from category_types t where t.code = 'M35' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124939,192,1,(select s.id from swimmers s where s.complete_name = 'PEZZOLI GIANLUCA' and s.year_of_birth = 1992),'',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124940,192,1,(select s.id from swimmers s where s.complete_name = 'RONZONI ALESSANDRO' and s.year_of_birth = 1984),'497872',2,(select t.id from category_types t where t.code = 'M35' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124941,192,1,(select s.id from swimmers s where s.complete_name = 'ROTA CAMILLA' and s.year_of_birth = 1989),'929339',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124942,192,1,(select s.id from swimmers s where s.complete_name = 'SESENA BARBARA' and s.year_of_birth = 1971),'53592',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124943,192,1,(select s.id from swimmers s where s.complete_name = 'STORCHI LORENZO' and s.year_of_birth = 1999),'',2,(select t.id from category_types t where t.code = 'U25' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124944,192,1,(select s.id from swimmers s where s.complete_name = 'TOFFANETTI LAURA' and s.year_of_birth = 1973),'43439',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'U'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124945,192,1,(select s.id from swimmers s where s.complete_name = 'VALCAVI LUCA' and s.year_of_birth = 1988),'385163',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE()),
(124946,192,1,(select s.id from swimmers s where s.complete_name = 'VEZZANI GIORGIA' and s.year_of_birth = 1995),'817133',2,(select t.id from category_types t where t.code = 'U25' and t.season_id = 192),(select t.id from entry_time_types t where t.code = 'P'),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 192),0,CURDATE(),CURDATE());

--
 -- Stagione FIN 2019-2020. Aggiunta dati per la tabella team_managers
 -- 
INSERT INTO team_managers (id,team_affiliation_id,user_id,lock_version,created_at,updated_at) VALUES 
(161,5726,2,0,CURDATE(),CURDATE());
